swagger: "2.0"
basePath: /
info:
  version: "2.0"
  title: API Gateway Resources
  description: ""
schemes:
  - http
paths:
  /api/v3/open-web/tenant/users/{bk_username}/display_info/:
    get:
      operationId: retrieve_user_display_info
      description: 查询用户展示信息
      tags: []
      responses:
        default:
          description: ""
      x-bk-apigateway-resource:
        isPublic: true
        allowApplyPermission: false
        matchSubpath: false
        backend:
          name: default
          method: get
          path: /api/v3/open-web/tenant/users/{bk_username}/display_info/
          matchSubpath: false
          timeout: 0
        pluginConfigs: []
        authConfig:
          userVerifiedRequired: true
          appVerifiedRequired: false
          resourcePermissionRequired: false
        descriptionEn: Query user's display information

  /api/v3/open-web/tenant/users/-/display_info/:
    get:
      operationId: batch_query_user_display_info
      description: 批量查询用户展示信息
      tags: []
      responses:
        default:
          description: ""
      x-bk-apigateway-resource:
        isPublic: true
        allowApplyPermission: false
        matchSubpath: false
        backend:
          name: default
          method: get
          path: /api/v3/open-web/tenant/users/-/display_info/
          matchSubpath: false
          timeout: 0
        pluginConfigs: []
        authConfig:
          userVerifiedRequired: true
          appVerifiedRequired: false
          resourcePermissionRequired: false
        descriptionEn: Batch query user's display information

  /api/v3/open-web/tenant/users/-/search/:
    get:
      operationId: search_user
      description: 搜索用户
      tags: []
      responses:
        default:
          description: ""
      x-bk-apigateway-resource:
        isPublic: true
        allowApplyPermission: false
        matchSubpath: false
        backend:
          name: default
          method: get
          path: /api/v3/open-web/tenant/users/-/search/
          matchSubpath: false
          timeout: 0
        pluginConfigs: []
        authConfig:
          userVerifiedRequired: true
          appVerifiedRequired: false
          resourcePermissionRequired: false
        descriptionEn: Search user

  /api/v3/open-web/tenant/users/-/lookup/:
    get:
      operationId: batch_lookup_user
      description: 批量查询用户
      tags: []
      responses:
        default:
          description: ""
      x-bk-apigateway-resource:
        isPublic: true
        allowApplyPermission: false
        matchSubpath: false
        backend:
          name: default
          method: get
          path: /api/v3/open-web/tenant/users/-/lookup/
          matchSubpath: false
          timeout: 0
        pluginConfigs: []
        authConfig:
          userVerifiedRequired: true
          appVerifiedRequired: false
          resourcePermissionRequired: false
        descriptionEn: Batch lookup users

  /api/v3/open-web/tenant/data-source-owner-tenants/:
    get:
      operationId: list_data_source_owner_tenant
      description: 获取本租户所有数据来源的租户信息
      tags: []
      responses:
        default:
          description: ""
      x-bk-apigateway-resource:
        isPublic: true
        allowApplyPermission: false
        matchSubpath: false
        backend:
          name: default
          method: get
          path: /api/v3/open-web/tenant/data-source-owner-tenants/
          matchSubpath: false
          timeout: 0
        pluginConfigs: []
        authConfig:
          userVerifiedRequired: true
          appVerifiedRequired: false
          resourcePermissionRequired: false
        descriptionEn: Get the tenant list of all data sources in this tenant

  /api/v3/open-web/tenant/departments/-/search/:
    get:
      operationId: search_department
      description: 搜索部门
      tags: []
      responses:
        default:
          description: ""
      x-bk-apigateway-resource:
        isPublic: true
        allowApplyPermission: false
        matchSubpath: false
        backend:
          name: default
          method: get
          path: /api/v3/open-web/tenant/departments/-/search/
          matchSubpath: false
          timeout: 0
        pluginConfigs: []
        authConfig:
          userVerifiedRequired: true
          appVerifiedRequired: false
          resourcePermissionRequired: false
        descriptionEn: Search department

  /api/v3/open-web/tenant/departments/-/lookup/:
    get:
      operationId: batch_lookup_department
      description: 批量查询部门
      tags: []
      responses:
        default:
          description: ""
      x-bk-apigateway-resource:
        isPublic: true
        allowApplyPermission: false
        matchSubpath: false
        backend:
          name: default
          method: get
          path: /api/v3/open-web/tenant/departments/-/lookup/
          matchSubpath: false
          timeout: 0
        pluginConfigs: []
        authConfig:
          userVerifiedRequired: true
          appVerifiedRequired: false
          resourcePermissionRequired: false
        descriptionEn: Batch lookup departments

  /api/v3/open-web/tenant/departments/{department_id}/children/:
    get:
      operationId: list_department_child
      description: 查询部门子部门信息
      tags: []
      responses:
        default:
          description: ""
      x-bk-apigateway-resource:
        isPublic: true
        allowApplyPermission: false
        matchSubpath: false
        backend:
          name: default
          method: get
          path: /api/v3/open-web/tenant/departments/{department_id}/children/
          matchSubpath: false
          timeout: 0
        pluginConfigs: []
        authConfig:
          userVerifiedRequired: true
          appVerifiedRequired: false
          resourcePermissionRequired: false
        descriptionEn: Query sub-departments information of the department

  /api/v3/open-web/tenant/departments/{department_id}/users/:
    get:
      operationId: list_department_user
      description: 查询部门所属用户信息
      tags: []
      responses:
        default:
          description: ""
      x-bk-apigateway-resource:
        isPublic: true
        allowApplyPermission: false
        matchSubpath: false
        backend:
          name: default
          method: get
          path: /api/v3/open-web/tenant/departments/{department_id}/users/
          matchSubpath: false
          timeout: 0
        pluginConfigs: []
        authConfig:
          userVerifiedRequired: true
          appVerifiedRequired: false
          resourcePermissionRequired: false
        descriptionEn: Query users information of the department

  /api/v3/open-web/tenant/virtual-users/:
    get:
      operationId: list_virtual_user
      description: 查询虚拟用户信息
      tags: []
      responses:
        default:
          description: ""
      x-bk-apigateway-resource:
        isPublic: true
        allowApplyPermission: false
        matchSubpath: false
        backend:
          name: default
          method: get
          path: /api/v3/open-web/tenant/virtual-users/
          matchSubpath: false
          timeout: 0
        pluginConfigs: []
        authConfig:
          userVerifiedRequired: true
          appVerifiedRequired: false
          resourcePermissionRequired: false
        descriptionEn: Query virtual users' information

  /:
    options:
      operationId: cors_options
      description: CORS 预检请求
      tags: []
      responses:
        default:
          description: ""
      x-bk-apigateway-resource:
        isPublic: false
        allowApplyPermission: false
        matchSubpath: true
        backend:
          name: default
          method: options
          path: /
          matchSubpath: true
          timeout: 0
        pluginConfigs: []
        authConfig:
          userVerifiedRequired: false
          appVerifiedRequired: false
          resourcePermissionRequired: false
        descriptionEn: CORS preflight request
