swagger: '2.0'
basePath: /
info:
  version: '0.1'
  title: API Gateway Resources
  description: ''
schemes:
- http
paths:
  /api/v1/login/check/:
    post:
      operationId: v1_login_login
      description: 登录信息校验
      tags:
      - v1
      responses:
        default:
          description: ''
      x-bk-apigateway-resource:
        isPublic: false
        allowApplyPermission: false
        matchSubpath: false
        backend:
          type: HTTP
          method: post
          path: /api/v1/login/check/
          matchSubpath: false
          timeout: 0
          upstreams: {}
          transformHeaders: {}
        authConfig:
          userVerifiedRequired: false
        disabledStages: []
  /api/v1/login/profile/:
    post:
      operationId: v1_login_upsert
      description: 登陆均为兼容代码
      tags:
      - v1
      responses:
        default:
          description: ''
      x-bk-apigateway-resource:
        isPublic: false
        allowApplyPermission: false
        matchSubpath: false
        backend:
          type: HTTP
          method: post
          path: /api/v1/login/profile/
          matchSubpath: false
          timeout: 0
          upstreams: {}
          transformHeaders: {}
        authConfig:
          userVerifiedRequired: false
        disabledStages: []
  /api/v1/login/profile/query/:
    post:
      operationId: v1_login_profile_batch_query
      description: 登陆均为兼容代码
      tags:
      - v1
      responses:
        default:
          description: ''
      x-bk-apigateway-resource:
        isPublic: false
        allowApplyPermission: false
        matchSubpath: false
        backend:
          type: HTTP
          method: post
          path: /api/v1/login/profile/query/
          matchSubpath: false
          timeout: 0
          upstreams: {}
          transformHeaders: {}
        authConfig:
          userVerifiedRequired: false
        disabledStages: []
  /api/v2/categories/:
    get:
      operationId: v2_categories_list
      description: 获取对象列表
      tags:
      - categories
      - v2
      responses:
        default:
          description: ''
      x-bk-apigateway-resource:
        isPublic: false
        allowApplyPermission: false
        matchSubpath: false
        backend:
          type: HTTP
          method: get
          path: /api/v2/categories/
          matchSubpath: false
          timeout: 0
          upstreams: {}
          transformHeaders: {}
        authConfig:
          userVerifiedRequired: false
        disabledStages: []
  /api/v2/departments/:
    get:
      operationId: v2_departments_list
      description: 获取对象列表
      tags:
      - departments
      - v2
      responses:
        default:
          description: ''
      x-bk-apigateway-resource:
        isPublic: false
        allowApplyPermission: false
        matchSubpath: false
        backend:
          type: HTTP
          method: get
          path: /api/v2/departments/
          matchSubpath: false
          timeout: 0
          upstreams: {}
          transformHeaders: {}
        authConfig:
          userVerifiedRequired: false
        disabledStages: []
  /api/v2/departments/{lookup_value}/:
    get:
      operationId: v2_departments_read
      description: ''
      tags:
      - departments
      - v2
      responses:
        default:
          description: ''
      x-bk-apigateway-resource:
        isPublic: false
        allowApplyPermission: false
        matchSubpath: false
        backend:
          type: HTTP
          method: get
          path: /api/v2/departments/{lookup_value}/
          matchSubpath: false
          timeout: 0
          upstreams: {}
          transformHeaders: {}
        authConfig:
          userVerifiedRequired: true
        disabledStages: []
  /api/v2/departments/{lookup_value}/profiles/:
    get:
      operationId: v2_departments_profiles_read
      description: 获取部门内的人员
      tags:
      - departments
      - v2
      responses:
        default:
          description: ''
      x-bk-apigateway-resource:
        isPublic: false
        allowApplyPermission: false
        matchSubpath: false
        backend:
          type: HTTP
          method: get
          path: /api/v2/departments/{lookup_value}/profiles/
          matchSubpath: false
          timeout: 0
          upstreams: {}
          transformHeaders: {}
        authConfig:
          userVerifiedRequired: false
        disabledStages: []
  /api/v2/edges/department_profile/:
    get:
      operationId: v2_edges_department_profile_list
      description: 获取对象列表
      tags:
      - edges
      - v2
      responses:
        default:
          description: ''
      x-bk-apigateway-resource:
        isPublic: false
        allowApplyPermission: false
        matchSubpath: false
        backend:
          type: HTTP
          method: get
          path: /api/v2/edges/department_profile/
          matchSubpath: false
          timeout: 0
          upstreams: {}
          transformHeaders: {}
        authConfig:
          userVerifiedRequired: false
        disabledStages: []
  /api/v2/edges/leader/:
    get:
      operationId: v2_edges_leader_list
      description: 获取对象列表
      tags:
      - edges
      - v2
      responses:
        default:
          description: ''
      x-bk-apigateway-resource:
        isPublic: false
        allowApplyPermission: false
        matchSubpath: false
        backend:
          type: HTTP
          method: get
          path: /api/v2/edges/leader/
          matchSubpath: false
          timeout: 0
          upstreams: {}
          transformHeaders: {}
        authConfig:
          userVerifiedRequired: false
        disabledStages: []
  /api/v2/profiles/:
    get:
      operationId: v2_profiles_list
      description: 获取用户列表
      tags:
      - profiles
      - v2
      responses:
        default:
          description: ''
      x-bk-apigateway-resource:
        isPublic: false
        allowApplyPermission: false
        matchSubpath: false
        backend:
          type: HTTP
          method: get
          path: /api/v2/profiles/
          matchSubpath: false
          timeout: 0
          upstreams: {}
          transformHeaders: {}
        authConfig:
          userVerifiedRequired: false
        disabledStages: []
  /api/v2/profiles/{lookup_value}/:
    get:
      operationId: v2_profiles_read
      description: 获取详细信息
      tags:
      - profiles
      - v2
      responses:
        default:
          description: ''
      x-bk-apigateway-resource:
        isPublic: false
        allowApplyPermission: false
        matchSubpath: false
        backend:
          type: HTTP
          method: get
          path: /api/v2/profiles/{lookup_value}/
          matchSubpath: false
          timeout: 0
          upstreams: {}
          transformHeaders: {}
        authConfig:
          userVerifiedRequired: false
        disabledStages: []
  /api/v2/profiles/{lookup_value}/departments/:
    get:
      operationId: v2_profiles_get_departments
      description: 获取用户所属部门信息
      tags:
      - profiles
      - v2
      responses:
        default:
          description: ''
      x-bk-apigateway-resource:
        isPublic: false
        allowApplyPermission: false
        matchSubpath: false
        backend:
          type: HTTP
          method: get
          path: /api/v2/profiles/{lookup_value}/departments/
          matchSubpath: false
          timeout: 0
          upstreams: {}
          transformHeaders: {}
        authConfig:
          userVerifiedRequired: false
        disabledStages: []
  /healthz/:
    get:
      operationId: healthz
      description: ''
      tags:
      - basic
      responses:
        default:
          description: ''
      x-bk-apigateway-resource:
        isPublic: true
        allowApplyPermission: true
        matchSubpath: false
        backend:
          type: HTTP
          method: get
          path: /healthz/
          matchSubpath: false
          timeout: 0
          upstreams: {}
          transformHeaders: {}
        authConfig:
          userVerifiedRequired: false
        disabledStages: []
  /ping/:
    get:
      operationId: ping
      description: ''
      tags:
      - basic
      responses:
        default:
          description: ''
      x-bk-apigateway-resource:
        isPublic: true
        allowApplyPermission: true
        matchSubpath: false
        backend:
          type: HTTP
          method: get
          path: /ping/
          matchSubpath: false
          timeout: 0
          upstreams: {}
          transformHeaders: {}
        authConfig:
          userVerifiedRequired: false
        disabledStages: []
