# Generated by Django 3.2.20 on 2023-08-07 03:31

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSourceDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data_source_id', models.IntegerField(verbose_name='数据源 ID')),
                ('code', models.CharField(blank=True, max_length=128, null=True, verbose_name='部门标识')),
                ('name', models.CharField(max_length=255, verbose_name='部门名称')),
                ('extras', models.JSONField(default=dict, verbose_name='自定义字段')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DataSourceUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data_source_id', models.IntegerField(verbose_name='数据源 ID')),
                ('username', models.CharField(max_length=128, verbose_name='用户名')),
                ('full_name', models.CharField(max_length=128, verbose_name='姓名')),
                ('email', models.EmailField(blank=True, default='', max_length=254, null=True, verbose_name='邮箱')),
                ('phone', models.CharField(max_length=32, verbose_name='手机号')),
                ('phone_country_code', models.CharField(blank=True, default='86', max_length=16, null=True, verbose_name='手机国际区号')),
                ('logo', models.TextField(blank=True, default='', max_length=256, null=True, verbose_name='Logo')),
                ('extras', models.JSONField(default=dict, verbose_name='自定义字段')),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('username', 'data_source_id')},
            },
        ),
        migrations.CreateModel(
            name='DataSourceUserLeaderRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.IntegerField(db_index=True, verbose_name='数据源用户 ID')),
                ('leader_id', models.IntegerField(db_index=True, verbose_name='数据源用户 Leader ID')),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('user_id', 'leader_id')},
            },
        ),
        migrations.CreateModel(
            name='DataSourceDepartmentUserRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department_id', models.IntegerField(db_index=True, verbose_name='数据源部门 ID')),
                ('user_id', models.IntegerField(db_index=True, verbose_name='数据源用户 ID')),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('department_id', 'user_id')},
            },
        ),
        migrations.CreateModel(
            name='LocalDataSourceIdentityInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('password', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='用户密码')),
                ('password_updated_at', models.DateTimeField(blank=True, null=True, verbose_name='密码最后更新时间')),
                ('password_expired_at', models.DateTimeField(blank=True, null=True, verbose_name='密码过期时间')),
                ('data_source_id', models.IntegerField(verbose_name='数据源 ID')),
                ('username', models.CharField(max_length=128, verbose_name='用户名')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='data_source_organization.datasourceuser')),
            ],
            options={
                'unique_together': {('username', 'data_source_id')},
            },
        ),
        migrations.CreateModel(
            name='DataSourceDepartmentRelation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='部门 ID')),
                ('data_source_id', models.IntegerField(verbose_name='数据源 ID')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='data_source_organization.datasourcedepartmentrelation')),
            ],
            options={
                'index_together': {('tree_id', 'lft', 'rght'), ('parent_id', 'tree_id', 'lft')},
            },
        ),
    ]
