# -*- coding: utf-8 -*-
"""
TencentBlueKing is pleased to support the open source community by making 蓝鲸智云-用户管理(Bk-User) available.
Copyright (C) 2017-2021 THL A29 Limited, a Tencent company. All rights reserved.
Licensed under the MIT License (the "License"); you may not use this file except in compliance with the License.
You may obtain a copy of the License at http://opensource.org/licenses/MIT
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
specific language governing permissions and limitations under the License.
"""
# Generated by Django 1.11.23 on 2021-03-16 10:14
from __future__ import unicode_literals

from bkuser_core.categories.constants import CategoryStatus
from django.db import migrations


def forwards_func(apps, schema_editor):
    """默认将当前已禁用的目录转换成 status 标记"""
    ProfileCategory = apps.get_model("categories", "ProfileCategory")
    for pc in ProfileCategory.objects.filter(enabled=False):
        pc.enabled = True
        pc.status = CategoryStatus.INACTIVE.value
        pc.save()


def reverse_func(apps, schema_editor):
    """回退"""
    ProfileCategory = apps.get_model("categories", "ProfileCategory")
    for pc in ProfileCategory.objects.filter(status=CategoryStatus.INACTIVE.value):
        pc.enabled = False
        pc.status = CategoryStatus.NORMAL.value
        pc.save()


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0007_auto_20210316_1806"),
    ]

    operations = [migrations.RunPython(forwards_func, reverse_func)]
