# Generated by Django 3.2.5 on 2021-08-26 07:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0010_auto_20210803_1026'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncTask',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='UUID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('successful', '成功'), ('failed', '失败'), ('running', '同步中')], default='running', max_length=16, verbose_name='状态')),
                ('type', models.CharField(choices=[('manual', '手动导入'), ('auto', '定时同步')], default='manual', max_length=16, verbose_name='触发类型')),
                ('operator', models.CharField(default='nobody', max_length=255, verbose_name='操作人')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.profilecategory', verbose_name='用户目录')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
