# Generated by Django 3.2.5 on 2021-12-09 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0011_synctask"),
    ]

    operations = [
        migrations.AddField(
            model_name="synctask",
            name="retried_count",
            field=models.IntegerField(default=0, verbose_name="重试次数"),
        ),
        migrations.AlterField(
            model_name="syncprogress",
            name="status",
            field=models.CharField(
                choices=[("successful", "成功"), ("failed", "失败"), ("running", "同步中"), ("retrying", "失败重试中")],
                default="running",
                max_length=16,
                verbose_name="状态",
            ),
        ),
        migrations.AlterField(
            model_name="synctask",
            name="status",
            field=models.CharField(
                choices=[("successful", "成功"), ("failed", "失败"), ("running", "同步中"), ("retrying", "失败重试中")],
                default="running",
                max_length=16,
                verbose_name="状态",
            ),
        ),
    ]
