# Generated by Django 3.2.5 on 2022-05-11 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0012_auto_20211209_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilecategory',
            name='type',
            field=models.CharField(max_length=32, verbose_name='类型'),
        ),
    ]
