# Generated by Django 3.2.5 on 2022-05-23 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('profiles', '0023_local_profile_add_account_expiration_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountExpirationNoticeRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('notice_date', models.DateField(verbose_name='账号过期通知时间')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile',
                                              verbose_name='登陆用户')),
            ],
            options={
                'verbose_name': '账号过期通知记录',
                'verbose_name_plural': '账号过期通知记录',
                'ordering': ['id'],
            },
        ),
]