# Generated by Django 3.2.15 on 2022-09-20 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0025_dynamic_field_add_account_expiration_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="create_time",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="username",
            field=models.CharField(max_length=255, verbose_name="用户名"),
        ),
    ]
