# Generated by Django 3.2.16 on 2023-05-19 06:37

from django.db import migrations


def forwards_func(apps, schema_editor):
    """修改内建字段信息"""
    DynamicFieldInfo = apps.get_model("profiles", "DynamicFieldInfo")

    DynamicFieldInfo.objects.filter(name='account_expiration_date').update(
        display_name='账号有效期',
        display_name_en='account_validity_period',
        display_name_zh_hans='账号有效期',
    )


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0026_auto_20220920_2251'),
    ]

    operations = [
        migrations.RunPython(forwards_func)
    ]
