# Generated by Django 3.2.15 on 2023-06-29 02:25

from django.db import migrations


def forwards_func(apps, schema_editor):
    """修改内建字段信息"""
    DynamicFieldInfo = apps.get_model("profiles", "DynamicFieldInfo")

    DynamicFieldInfo.objects.filter(name='account_expiration_date').update(display_name_en='AccountValidityPeriod')
    DynamicFieldInfo.objects.filter(name='last_login_time').update(display_name_en='LastLoginTime')
    DynamicFieldInfo.objects.filter(name='create_time').update(display_name_en='CreateTime')


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0027_dynamic_field_change_account_expiration_date'),
    ]

    operations = [
        migrations.RunPython(forwards_func)
    ]
