# Generated by Django 4.2.17 on 2025-05-26 12:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0029_alter_profile_index_together_alter_profile_time_zone"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="profile",
            index=models.Index(
                fields=["domain", "email"], name="profiles_pr_domain_fba706_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="profile",
            index=models.Index(
                fields=["domain", "telephone"], name="profiles_pr_domain_4a6222_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="profile",
            index=models.Index(
                fields=["domain", "username"], name="profiles_pr_domain_a6c99e_idx"
            ),
        ),
    ]
