# Generated by Django 3.2.21 on 2023-11-09 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BkToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='登录票据')),
                ('is_logout', models.BooleanField(default=False, verbose_name='票据是否已经执行过退出登录操作')),
                ('inactive_expires_at', models.IntegerField(default=0, verbose_name='无操作失效时间戳')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
