# Generated by Django 4.2.16 on 2025-12-01 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bktoken',
            name='user_id',
            field=models.CharField(db_index=True, default='', max_length=255, verbose_name='用户ID'),
        ),
    ]
