{{- if .Values.global.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "bk-user.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "bk-user.labels" . | nindent 4 }}
spec:
  {{- if .Values.global.serviceMonitor.jobLabel }}
  jobLabel: {{ .Values.global.serviceMonitor.jobLabel }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "bk-user.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: "/metrics"
      {{- if .Values.global.serviceMonitor.interval }}
      interval: {{ .Values.global.serviceMonitor.interval }}
      {{- end }}
      {{- if .Values.global.serviceMonitor.scrapeTimeout }}
      scrapeTimeout: {{ .Values.global.serviceMonitor.scrapeTimeout }}
      {{- end }}
      {{- if hasKey .Values.global.serviceMonitor "honorLabels" }}
      honorLabels: {{ .Values.global.serviceMonitor.honorLabels }}
      {{- end }}
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
{{- end }}
