{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bk-login
  labels:
    {{- include "bk-user.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: bk-login-role
rules:
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bk-login-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: bk-login-role
subjects:
- kind: ServiceAccount
  name: bk-login
  namespace: {{ default "default" .Release.Namespace }}
{{- end }}
