# coding: utf-8

"""
    蓝鲸用户管理 API

    User management APIs for BlueKing  # noqa: E501

    OpenAPI spec version: v2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import bkuser_sdk
from api.profiles_api import ProfilesApi  # noqa: E501
from bkuser_sdk.rest import ApiException


class TestProfilesApi(unittest.TestCase):
    """ProfilesApi unit test stubs"""

    def setUp(self):
        self.api = api.profiles_api.ProfilesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_v2_profiles_create(self):
        """Test case for v2_profiles_create

        """
        pass

    def test_v2_profiles_delete(self):
        """Test case for v2_profiles_delete

        """
        pass

    def test_v2_profiles_generate_token(self):
        """Test case for v2_profiles_generate_token

        """
        pass

    def test_v2_profiles_get_departments(self):
        """Test case for v2_profiles_get_departments

        """
        pass

    def test_v2_profiles_get_leaders(self):
        """Test case for v2_profiles_get_leaders

        """
        pass

    def test_v2_profiles_list(self):
        """Test case for v2_profiles_list

        """
        pass

    def test_v2_profiles_modify_password(self):
        """Test case for v2_profiles_modify_password

        """
        pass

    def test_v2_profiles_partial_update(self):
        """Test case for v2_profiles_partial_update

        """
        pass

    def test_v2_profiles_read(self):
        """Test case for v2_profiles_read

        """
        pass

    def test_v2_profiles_update(self):
        """Test case for v2_profiles_update

        """
        pass

    def test_v2_retrieve_by_token(self):
        """Test case for v2_retrieve_by_token

        """
        pass


if __name__ == '__main__':
    unittest.main()
