# coding: utf-8

"""
    蓝鲸用户管理 API

    User management APIs for BlueKing  # noqa: E501

    OpenAPI spec version: v2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import bkuser_sdk
from api.v1_api import V1Api  # noqa: E501
from bkuser_sdk.rest import ApiException


class TestV1Api(unittest.TestCase):
    """V1Api unit test stubs"""

    def setUp(self):
        self.api = api.v1_api.V1Api()  # noqa: E501

    def tearDown(self):
        pass

    def test_v1_login_login(self):
        """Test case for v1_login_login

        """
        pass

    def test_v1_login_profile_batch_query(self):
        """Test case for v1_login_profile_batch_query

        """
        pass

    def test_v1_login_upsert(self):
        """Test case for v1_login_upsert

        """
        pass


if __name__ == '__main__':
    unittest.main()
