# coding: utf-8

"""
    蓝鲸用户管理 API

    User management APIs for BlueKing  # noqa: E501

    OpenAPI spec version: v2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import bkuser_sdk
from models.reset_password_log import ResetPasswordLog  # noqa: E501
from bkuser_sdk.rest import ApiException


class TestResetPasswordLog(unittest.TestCase):
    """ResetPasswordLog unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testResetPasswordLog(self):
        """Test ResetPasswordLog"""
        # FIXME: construct object with mandatory attributes with example values
        # model = bkuser_sdk.models.reset_password_log.ResetPasswordLog()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
