# coding: utf-8

"""
    蓝鲸用户管理 API

    蓝鲸用户管理后台服务 API  # noqa: E501

    OpenAPI spec version: v2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import bkuser_sdk
from models.department_update import DepartmentUpdate  # noqa: E501
from bkuser_sdk.rest import ApiException


class TestDepartmentUpdate(unittest.TestCase):
    """DepartmentUpdate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDepartmentUpdate(self):
        """Test DepartmentUpdate"""
        # FIXME: construct object with mandatory attributes with example values
        # model = bkuser_sdk.models.department_update.DepartmentUpdate()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
