# coding: utf-8

"""
    蓝鲸用户管理 API

    User management APIs for BlueKing  # noqa: E501

    OpenAPI spec version: v2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import bkuser_sdk
from api.dynamic_fields_api import DynamicFieldsApi  # noqa: E501
from bkuser_sdk.rest import ApiException


class TestDynamicFieldsApi(unittest.TestCase):
    """DynamicFieldsApi unit test stubs"""

    def setUp(self):
        self.api = api.dynamic_fields_api.DynamicFieldsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_v2_dynamic_fields_create(self):
        """Test case for v2_dynamic_fields_create

        """
        pass

    def test_v2_dynamic_fields_delete(self):
        """Test case for v2_dynamic_fields_delete

        """
        pass

    def test_v2_dynamic_fields_list(self):
        """Test case for v2_dynamic_fields_list

        """
        pass

    def test_v2_dynamic_fields_partial_update(self):
        """Test case for v2_dynamic_fields_partial_update

        """
        pass

    def test_v2_dynamic_fields_read(self):
        """Test case for v2_dynamic_fields_read

        """
        pass

    def test_v2_dynamic_fields_update(self):
        """Test case for v2_dynamic_fields_update

        """
        pass


if __name__ == '__main__':
    unittest.main()
