# coding: utf-8

"""
    蓝鲸用户管理 API

    User management APIs for BlueKing  # noqa: E501

    OpenAPI spec version: v2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import bkuser_sdk
from models.general_log import GeneralLog  # noqa: E501
from bkuser_sdk.rest import ApiException


class TestGeneralLog(unittest.TestCase):
    """GeneralLog unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGeneralLog(self):
        """Test GeneralLog"""
        # FIXME: construct object with mandatory attributes with example values
        # model = bkuser_sdk.models.general_log.GeneralLog()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
