# coding: utf-8

"""
    蓝鲸用户管理 API

    User management APIs for BlueKing  # noqa: E501

    OpenAPI spec version: v2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import bkuser_sdk
from api.pong_api import PongApi  # noqa: E501
from bkuser_sdk.rest import ApiException


class TestPongApi(unittest.TestCase):
    """PongApi unit test stubs"""

    def setUp(self):
        self.api = api.pong_api.PongApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_pong(self):
        """Test case for pong

        """
        pass


if __name__ == '__main__':
    unittest.main()
