# coding: utf-8

"""
    蓝鲸用户管理 API

    User management APIs for BlueKing  # noqa: E501

    OpenAPI spec version: v2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import bkuser_sdk
from api.settings_api import SettingsApi  # noqa: E501
from bkuser_sdk.rest import ApiException


class TestSettingsApi(unittest.TestCase):
    """SettingsApi unit test stubs"""

    def setUp(self):
        self.api = api.settings_api.SettingsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_v2_settings_create(self):
        """Test case for v2_settings_create

        """
        pass

    def test_v2_settings_delete(self):
        """Test case for v2_settings_delete

        """
        pass

    def test_v2_settings_list(self):
        """Test case for v2_settings_list

        """
        pass

    def test_v2_settings_partial_update(self):
        """Test case for v2_settings_partial_update

        """
        pass

    def test_v2_settings_read(self):
        """Test case for v2_settings_read

        """
        pass

    def test_v2_settings_update(self):
        """Test case for v2_settings_update

        """
        pass


if __name__ == '__main__':
    unittest.main()
