# coding: utf-8

"""
    蓝鲸用户管理 API

    User management APIs for BlueKing  # noqa: E501

    OpenAPI spec version: v2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import bkuser_sdk
from api.shortcuts_api import ShortcutsApi  # noqa: E501
from bkuser_sdk.rest import ApiException


class TestShortcutsApi(unittest.TestCase):
    """ShortcutsApi unit test stubs"""

    def setUp(self):
        self.api = api.shortcuts_api.ShortcutsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_v2_shortcuts_departments_tops_read(self):
        """Test case for v2_shortcuts_departments_tops_read

        """
        pass


if __name__ == '__main__':
    unittest.main()
