# coding: utf-8

"""
    蓝鲸用户管理 API

    User management APIs for BlueKing  # noqa: E501

    OpenAPI spec version: v2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import bkuser_sdk
from api.edges_api import EdgesApi  # noqa: E501
from bkuser_sdk.rest import ApiException


class TestEdgesApi(unittest.TestCase):
    """EdgesApi unit test stubs"""

    def setUp(self):
        self.api = api.edges_api.EdgesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_v2_edges_department_profile_list(self):
        """Test case for v2_edges_department_profile_list

        """
        pass

    def test_v2_edges_leader_list(self):
        """Test case for v2_edges_leader_list

        """
        pass


if __name__ == '__main__':
    unittest.main()
