# coding: utf-8

"""
    蓝鲸用户管理 API

    User management APIs for BlueKing  # noqa: E501

    OpenAPI spec version: v2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import bkuser_sdk
from api.categories_api import CategoriesApi  # noqa: E501
from bkuser_sdk.rest import ApiException


class TestCategoriesApi(unittest.TestCase):
    """CategoriesApi unit test stubs"""

    def setUp(self):
        self.api = api.categories_api.CategoriesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_v2_categories_create(self):
        """Test case for v2_categories_create

        """
        pass

    def test_v2_categories_delete(self):
        """Test case for v2_categories_delete

        """
        pass

    def test_v2_categories_import_data_file(self):
        """Test case for v2_categories_import_data_file

        """
        pass

    def test_v2_categories_list(self):
        """Test case for v2_categories_list

        """
        pass

    def test_v2_categories_list_metas(self):
        """Test case for v2_categories_list_metas

        """
        pass

    def test_v2_categories_partial_update(self):
        """Test case for v2_categories_partial_update

        """
        pass

    def test_v2_categories_read(self):
        """Test case for v2_categories_read

        """
        pass

    def test_v2_categories_sync(self):
        """Test case for v2_categories_sync

        """
        pass

    def test_v2_categories_test_connection(self):
        """Test case for v2_categories_test_connection

        """
        pass

    def test_v2_categories_test_fetch_data(self):
        """Test case for v2_categories_test_fetch_data

        """
        pass

    def test_v2_categories_update(self):
        """Test case for v2_categories_update

        """
        pass


if __name__ == '__main__':
    unittest.main()
