# coding: utf-8

"""
    蓝鲸用户管理 API

    User management APIs for BlueKing  # noqa: E501

    OpenAPI spec version: v2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import bkuser_sdk
from api.setting_metas_api import SettingMetasApi  # noqa: E501
from bkuser_sdk.rest import ApiException


class TestSettingMetasApi(unittest.TestCase):
    """SettingMetasApi unit test stubs"""

    def setUp(self):
        self.api = api.setting_metas_api.SettingMetasApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_v2_setting_metas_create(self):
        """Test case for v2_setting_metas_create

        """
        pass

    def test_v2_setting_metas_delete(self):
        """Test case for v2_setting_metas_delete

        """
        pass

    def test_v2_setting_metas_list(self):
        """Test case for v2_setting_metas_list

        """
        pass

    def test_v2_setting_metas_partial_update(self):
        """Test case for v2_setting_metas_partial_update

        """
        pass

    def test_v2_setting_metas_read(self):
        """Test case for v2_setting_metas_read

        """
        pass

    def test_v2_setting_metas_update(self):
        """Test case for v2_setting_metas_update

        """
        pass


if __name__ == '__main__':
    unittest.main()
