spec_version: 2

release:
  # 发布版本号
  version: 0.0.1
  title: "bk-user"
  comment: "bk-user"

apigateway:
  description: "用户管理 OpenAPI 网关"
  description_en: "User Management OpenAPI Gateway"
  is_public: true
  api_type: 1
  maintainers:
    - "admin"

stages:
  - name: "prod"
    description: "生产环境"
    description_en: "environment of production"
    backends:
      - name: "default"
        config:
          timeout: 30
          loadbalance: "roundrobin"
          hosts:
            # 网关调用后端服务的默认域名或IP，不包含Path，比如：http://api.example.com
            - host: "http://bkuser"
              weight: 100

# 资源文档
# 资源文档的目录格式样例如下，en 为英文文档，zh 为中文文档：
# ./
# - en
#   - anything.md
# - zh
#   - anything.md
resource_docs:
  basedir: "support-files/bk-user-apigateway/apidocs/"

# 主动授权，网关主动给应用，添加访问网关所有资源的权限
grant_permissions:
 - bk_app_code: "bk-cmsi"
   grant_dimension: "resource"
   resource_names:
     - "batch_query_user_sensitive_info"
