# Generated by Django 3.2.13 on 2022-06-29 08:10

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettingsMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=64, verbose_name='全局配置键')),
                ('enabled', models.BooleanField(default=True)),
                ('required', models.BooleanField(default=True, verbose_name='是否必要')),
                ('namespace', models.CharField(choices=[('general', '通用'), ('two_factor_authentication', '双因子认证')], db_index=True, default='general', max_length=32, verbose_name='命名空间')),
                ('example', jsonfield.fields.JSONField(default='', verbose_name='示例')),
                ('default', jsonfield.fields.JSONField(default=None, verbose_name='默认值')),
                ('choices', jsonfield.fields.JSONField(default=[], verbose_name='可选值')),
                ('region', models.CharField(default='default', max_length=32, verbose_name='领域')),
            ],
            options={
                'verbose_name': '全局配置元信息表',
                'verbose_name_plural': '全局配置元信息表',
                'ordering': ['-create_time'],
                'unique_together': {('key', 'namespace')},
            },
        ),
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('value', jsonfield.fields.JSONField(default={}, verbose_name='全局配置内容')),
                ('enabled', models.BooleanField(default=True)),
                ('meta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='global_settings.globalsettingsmeta')),
            ],
            options={
                'verbose_name': '全局配置表',
                'verbose_name_plural': '全局配置表',
                'ordering': ['-create_time'],
                'unique_together': {('meta',)},
            },
        ),
    ]
