# Generated by Django 3.2.13 on 2022-06-17 06:13

from django.db import migrations

from bkuser_core.global_settings.constants import (
    TWO_FACTOR_AUTHENTICATION_META,
    GlobalSettingsEnableNamespaces,
    AUTHENTICATION_TYPE_META
)


def init_global_meta(apps):
    global_setting_meta = apps.get_model("global_settings", "GlobalSettingsMeta")

    # 全局配置元数据初始化
    general_instance = global_setting_meta.objects.create(
        required=True,
        **AUTHENTICATION_TYPE_META
    )
    global_settings_meta = [general_instance]

    for item in TWO_FACTOR_AUTHENTICATION_META:
        instance = global_setting_meta.objects.create(
            namespace=GlobalSettingsEnableNamespaces.TWO_FACTOR_AUTHENTICATION.value,
            required=True,
            **item
        )
        global_settings_meta.append(instance)
    return global_settings_meta


def init_global_settings(apps, settings_meta):
    global_settings = apps.get_model("global_settings", "GlobalSettings")

    for instance in settings_meta:
        global_settings.objects.create(
            value=instance.default,
            meta=instance
        )


def forwards_func(apps, schema_editor):
    global_settings_meta = init_global_meta(apps)
    init_global_settings(apps, settings_meta=global_settings_meta)


class Migration(migrations.Migration):
    dependencies = [
        ('global_settings', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forwards_func)
    ]
