spec_version: 2

release:
  # 发布版本号
  version: 0.0.2
  title: "bk-login"
  comment: "bk-login"

apigateway:
  description: "登录 OpenAPI 网关"
  description_en: "Login OpenAPI Gateway"
  allow_delete_sensitive_params: false
  is_public: true
  maintainers:
    - "admin"

stages:
  - name: "prod"
    description: "生产环境"
    description_en: "environment of production"
    backends:
      - name: "default"
        config:
          timeout: 30
          loadbalance: "roundrobin"
          hosts:
          # 网关调用后端服务的默认域名或IP，不包含Path，比如：http://api.example.com
           - host: "http://bklogin"
             weight: 100

# 资源文档
# 资源文档的目录格式样例如下，en 为英文文档，zh 为中文文档：
# ./
# - en
#   - anything.md
# - zh
#   - anything.md
resource_docs:
  basedir: "support-files/apidocs/"

# 主动授权，网关主动给应用，添加访问网关所有资源的权限
#grant_permissions:
#  - bk_app_code: "{{ settings.BK_APP_CODE }}"
#    grant_dimension: "gateway"
