# Generated by Django 3.2.25 on 2024-04-19 03:10

import bkuser.apps.idp.constants
import bkuser.utils.uuid
import blue_krill.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IdpPlugin',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False, verbose_name='认证源插件唯一标识')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='认证源插件名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('logo', models.TextField(blank=True, default='', null=True, verbose_name='Logo')),
            ],
        ),
        migrations.CreateModel(
            name='Idp',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.CharField(blank=True, max_length=128, null=True)),
                ('updater', models.CharField(blank=True, max_length=128, null=True)),
                ('id', models.CharField(default=bkuser.utils.uuid.generate_uuid, max_length=128, primary_key=True, serialize=False, verbose_name='认证源标识')),
                ('name', models.CharField(max_length=128, verbose_name='认证源名称')),
                ('owner_tenant_id', models.CharField(db_index=True, max_length=64, verbose_name='归属租户')),
                ('status', models.CharField(choices=[('enabled', '启用'), ('disabled', '未启用')], default=bkuser.apps.idp.constants.IdpStatus['ENABLED'], max_length=32, verbose_name='认证源状态')),
                ('plugin_config', models.JSONField(default=dict, verbose_name='插件配置')),
                ('data_source_match_rules', models.JSONField(default=list, verbose_name='匹配规则')),
                ('data_source_id', models.IntegerField(verbose_name='数据源 ID')),
                ('plugin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='idp.idpplugin')),
            ],
            options={
                'ordering': ['created_at'],
                'unique_together': {('data_source_id', 'plugin', 'owner_tenant_id'), ('name', 'owner_tenant_id')},
            },
        ),
        migrations.CreateModel(
            name='IdpSensitiveInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=255, verbose_name='配置字段路径')),
                ('value', blue_krill.models.fields.EncryptField(max_length=255, verbose_name='敏感配置数据')),
                ('idp', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.PROTECT, to='idp.idp')),
            ],
            options={
                'unique_together': {('idp', 'key')},
            },
        ),
    ]
