# Generated by Django 3.2.20 on 2023-11-13 09:45

import bkuser.apps.idp.constants
import bkuser.utils.uuid
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IdpPlugin',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False, verbose_name='认证源插件唯一标识')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='认证源插件名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('logo', models.TextField(blank=True, default='', null=True, verbose_name='Logo')),
            ],
        ),
        migrations.CreateModel(
            name='Idp',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.CharField(blank=True, max_length=128, null=True)),
                ('updater', models.CharField(blank=True, max_length=128, null=True)),
                ('id', models.CharField(default=bkuser.utils.uuid.generate_uuid, max_length=128, primary_key=True, serialize=False, verbose_name='认证源标识')),
                ('name', models.CharField(max_length=128, verbose_name='认证源名称')),
                ('owner_tenant_id', models.CharField(db_index=True, max_length=64, verbose_name='归属租户')),
                ('status', models.CharField(choices=[('enabled', '启用'), ('disabled', '未启用')], default=bkuser.apps.idp.constants.IdpStatus['ENABLED'], max_length=32, verbose_name='认证源状态')),
                ('plugin_config', models.JSONField(default=dict, verbose_name='插件配置')),
                ('data_source_match_rules', models.JSONField(default=list, verbose_name='匹配规则')),
                ('allow_bind_scopes', models.JSONField(default=list, verbose_name='允许范围')),
                ('plugin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='idp.idpplugin')),
            ],
            options={
                'unique_together': {('name', 'owner_tenant_id')},
            },
        ),
    ]
