# Generated by Django 3.2.20 on 2023-10-25 08:42
from django.conf import settings
from django.db import migrations

from bkuser.idp_plugins.constants import BuiltinIdpPluginEnum
from bkuser.utils.base64 import load_image_as_base64


def forwards_func(apps, schema_editor):
    """初始化本地数据源插件"""

    IdpPlugin = apps.get_model("idp", "IdpPlugin")

    IdpPlugin.objects.get_or_create(
        id=BuiltinIdpPluginEnum.LOCAL,
        defaults={
            "name": BuiltinIdpPluginEnum.get_choice_label(BuiltinIdpPluginEnum.LOCAL),
            "description": "使用本地DB数据源提供的用户名和密码进行认证",
            "logo": load_image_as_base64(settings.BASE_DIR / "bkuser/idp_plugins/local/logo.png")
        }
    )

    IdpPlugin.objects.get_or_create(
        id=BuiltinIdpPluginEnum.WECOM,
        defaults={
            "name": BuiltinIdpPluginEnum.get_choice_label(BuiltinIdpPluginEnum.WECOM),
            "description": "使用腾讯企业微信进行企业身份认证",
            "logo": load_image_as_base64(settings.BASE_DIR / "bkuser/idp_plugins/wecom/logo.png")
        }
    )


class Migration(migrations.Migration):

    dependencies = [
        ('idp', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forwards_func)
    ]
