# Generated by Django 3.2.20 on 2023-11-22 03:09

import blue_krill.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('idp', '0002_init_builtin_idp_plugin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='idp',
            options={'ordering': ['created_at']},
        ),
        migrations.CreateModel(
            name='IdpSensitiveInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=255, verbose_name='配置字段路径')),
                ('value', blue_krill.models.fields.EncryptField(max_length=255, verbose_name='敏感配置数据')),
                ('idp', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.PROTECT, to='idp.idp')),
            ],
            options={
                'unique_together': {('idp', 'key')},
            },
        ),
    ]
