# Generated by Django 3.2.25 on 2024-07-31 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idp', '0002_init_builtin_idp_plugin'),
    ]

    operations = [
        migrations.AddField(
            model_name='idpplugin',
            name='description_en_us',
            field=models.TextField(blank=True, default='', null=True, verbose_name='描述'),
        ),
        migrations.AddField(
            model_name='idpplugin',
            name='description_zh_cn',
            field=models.TextField(blank=True, default='', null=True, verbose_name='描述'),
        ),
        migrations.AddField(
            model_name='idpplugin',
            name='name_en_us',
            field=models.CharField(max_length=128, null=True, unique=True, verbose_name='认证源插件名称'),
        ),
        migrations.AddField(
            model_name='idpplugin',
            name='name_zh_cn',
            field=models.CharField(max_length=128, null=True, unique=True, verbose_name='认证源插件名称'),
        ),
    ]
