# Generated by Codex on 2026-06-23

from django.db import migrations, models
import django.db.models.deletion


def forwards_func(apps, schema_editor):
    Idp = apps.get_model("idp", "Idp")
    IdpDataSourceRelation = apps.get_model("idp", "IdpDataSourceRelation")
    DataSource = apps.get_model("data_source", "DataSource")

    existing_data_source_ids = set(DataSource.objects.values_list("id", flat=True))

    for idp in Idp.objects.all().iterator():
        rules = idp.data_source_match_rules or []
        relation_rules = {}
        for rule in rules:
            data_source_id = rule.get("data_source_id")
            if not data_source_id or data_source_id not in existing_data_source_ids:
                continue

            relation_rules[data_source_id] = rule.get("field_compare_rules") or []

        if (
            idp.data_source_id
            and idp.data_source_id in existing_data_source_ids
            and idp.data_source_id not in relation_rules
        ):
            relation_rules[idp.data_source_id] = []

        for data_source_id, field_compare_rules in relation_rules.items():
            IdpDataSourceRelation.objects.get_or_create(
                idp_id=idp.id,
                data_source_id=data_source_id,
                defaults={
                    "idp_owner_tenant_id": idp.owner_tenant_id,
                    "field_compare_rules": field_compare_rules,
                },
            )


class Migration(migrations.Migration):
    dependencies = [
        ("data_source", "0003_datasource_multi_source_support"),
        ("idp", "0002_init_builtin_idp_plugin"),
    ]

    operations = [
        migrations.CreateModel(
            name="IdpDataSourceRelation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("idp_owner_tenant_id", models.CharField(db_index=True, max_length=64, verbose_name="认证源归属租户")),
                ("field_compare_rules", models.JSONField(default=list, verbose_name="字段匹配规则")),
                (
                    "data_source",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="idp_relations",
                        to="data_source.datasource",
                    ),
                ),
                (
                    "idp",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_source_relations",
                        to="idp.idp",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
                "indexes": [
                    models.Index(fields=["idp_owner_tenant_id", "data_source"], name="idp_idpdata_idp_ow_5f0ca5_idx"),
                    models.Index(fields=["data_source", "idp"], name="idp_idpdata_data_so_12f07d_idx"),
                ],
                "unique_together": {("idp", "data_source")},
            },
        ),
        migrations.RunPython(forwards_func, migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name="idp",
            unique_together={("name", "owner_tenant_id")},
        ),
        migrations.RemoveField(
            model_name="idp",
            name="data_source_match_rules",
        ),
        migrations.RemoveField(
            model_name="idp",
            name="data_source_id",
        ),
    ]
