# Generated by Django 3.2.25 on 2024-07-31 07:58

from django.db import migrations

from bkuser.idp_plugins.constants import BuiltinIdpPluginEnum


def forwards_func(apps, schema_editor):
    """添加 idp 翻译"""

    IdpPlugin = apps.get_model("idp", "IdpPlugin")

    # 本地账密认证源插件
    IdpPlugin.objects.filter(id=BuiltinIdpPluginEnum.LOCAL).update(
        name_zh_cn=BuiltinIdpPluginEnum.get_choice_label(BuiltinIdpPluginEnum.LOCAL),
        description_zh_cn="使用本地DB数据源提供的用户名和密码进行认证",
        name_en_us="Local Account Password",
        description_en_us="Authenticate using username and password provided by the local DB data source",
    )

    # 企业微信认证源插件
    IdpPlugin.objects.filter(id=BuiltinIdpPluginEnum.WECOM).update(
        name_zh_cn=BuiltinIdpPluginEnum.get_choice_label(BuiltinIdpPluginEnum.WECOM),
        description_zh_cn="使用腾讯企业微信进行企业身份认证",
        name_en_us="WeCom Identity Provider",
        description_en_us="Authenticate using Tencent WeCom for corporate identity authentication",
    )

class Migration(migrations.Migration):

    dependencies = [
        ('idp', '0003_add_translation_fields'),
    ]

    operations = [migrations.RunPython(forwards_func)]
