# Generated by Django 3.2.20 on 2024-01-24 02:15

import bkuser.apps.idp.constants
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idp', '0003_auto_20231122_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idp',
            name='status',
            field=models.CharField(choices=[('enabled', '启用'), ('disabled', '未启用'), ('deleted', '软删除')], default=bkuser.apps.idp.constants.IdpStatus['ENABLED'], max_length=32, verbose_name='认证源状态'),
        ),
    ]
