# Generated by Django 3.2.15 on 2023-06-29 09:12

from django.db import migrations

from bkuser_core.categories.constants import CategoryStatus
from bkuser_core.categories.models import ProfileCategory
from bkuser_core.recycle_bin.constants import RecycleBinObjectType
from bkuser_core.recycle_bin.models import RecycleBin


def forwards_func(apps, schema_editor):
    """存量已删除目录，增加回收站映射关系"""
    # apps.get_model的形式的delete是硬删除
    del_categories = ProfileCategory.objects.filter(status=CategoryStatus.INACTIVE.value, enabled=False)
    # 适配新的category.delete(), 并添加相应回收站记录
    recycle_bin_relationships: list = []
    for item in del_categories:
        # 原本的delete是将目录状态变为enabled=0，status=inactived
        # 新的delete 目录状态变为enabled=0，status=deleted
        item.delete()

        recycle_bin_record = RecycleBin(
            object_id=item.id,
            object_type=RecycleBinObjectType.CATEGORY.value,
            operator="admin"
        )
        recycle_bin_relationships.append(recycle_bin_record)

    if recycle_bin_relationships:
        RecycleBin.objects.bulk_create(recycle_bin_relationships)


class Migration(migrations.Migration):

    dependencies = [
        ('recycle_bin', '0001_initial'),
        ('categories', '0014_alter_profilecategory_status'),
    ]

    operations = [
        migrations.RunPython(forwards_func)
    ]
