[project]
name = "bk-user"
description = ""
version = "0.1.0"
readme = "README.md"
dynamic = ["classifiers"]
authors = [{ name = "TencentBlueKing", email = "contactus_bk@tencent.com" }]
requires-python = ">=3.11,<3.12"
dependencies = [
    "django==4.2.23",
    "djangorestframework==3.16.0",
    "celery==5.5.3",
    # Note: 不可以升级到 2.8.1 版本，存在 mysql 5.7 兼容性问题，虽然官方 master 分支已修复，但未出新版本
    "django-celery-beat==2.8.0",
    "django-celery-results==2.6.0",
    "pymysql==1.1.1",
    "requests==2.32.5",
    "gunicorn==23.0.0",
    "gevent==25.5.1",
    "django-environ==0.12.0",
    "django-cors-headers==4.7.0",
    "django-prometheus==2.4.1",
    "whitenoise==6.9.0",
    "werkzeug==3.1.3",
    "python-json-logger==3.3.0",
    "concurrent-log-handler==0.9.25",
    "drf-yasg==1.21.10",
    "blue-krill==2.1.3",
    "django-mptt==0.17.0",
    "redis==6.2.0",
    "django-redis==6.0.0",
    "pydantic[email]==2.11.7",
    "zxcvbn==4.5.0",
    "phonenumbers==9.0.9",
    "jsonref==1.1.0",
    "openpyxl==3.1.5",
    "tongsuopy-crayon==1.0.2b6",
    "sentry-sdk==2.33.0",
    "bk-notice-sdk==1.4.2",
    "opentelemetry-api==1.35.0",
    "opentelemetry-sdk==1.35.0",
    "opentelemetry-proto==1.35.0",
    "opentelemetry-exporter-otlp==1.35.0",
    "opentelemetry-instrumentation-django==0.56b0",
    "opentelemetry-instrumentation-dbapi==0.56b0",
    "opentelemetry-instrumentation-redis==0.56b0",
    "opentelemetry-instrumentation-requests==0.56b0",
    "opentelemetry-instrumentation-celery==0.56b0",
    "opentelemetry-instrumentation-logging==0.56b0",
    "django-modeltranslation==0.19.16",
    "ldap3==2.9.1",
    "nanoid==2.0.0",
    "apigw-manager[cryptography]==4.1.0",
    "defusedxml==0.7.1",
    # Note: setuptools > 80.8.0 will issue pkg_resources warnings when executing Python-related commands.
    "setuptools==80.8.0",
]

[dependency-groups]
dev = [
    "ruff>=0.15.5,<0.16.0",
    "mypy>=1.10.1,<2.0.0",
    "types-requests>=2.31.0.1,<3.0.0",
    "pytest>=8.3.3,<9.0.0",
    "pytest-django>=4.9.0,<5.0.0",
    "types-pytz>=2024.2.0.20241003,<2025.0.0.0",
    "import-linter>=2.1,<3.0.0",
    "types-redis>=4.6.0.20241004,<5.0.0.0",
    "types-pymysql>=1.1.0.20240524,<2.0.0"
]

[tool.uv]
package = false

[[tool.uv.index]]
# url = "https://mirrors.tencent.com/pypi/simple"
url = "https://pypi.org/simple/"
default = true

[tool.mypy]
ignore_missing_imports = true
show_error_codes = true
strict_optional = true
pretty = true
check_untyped_defs = true
namespace_packages = true

[[tool.mypy.overrides]]
module = [
    "*.migrations.*",
    "bkuser.utils.tree"
]
ignore_errors = true

[tool.ruff]
# Same as Black.
line-length = 119
# show an enumeration of all autofixed lint violations
# show-fixes = true
# show source code snippets when reporting lint violations
# show-source = true
# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
    "*/migrations/*",
]
force-exclude = true

[tool.ruff.format]
# Like Black, indent with spaces, rather than tabs.
indent-style = "space"
# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false
# Like Black, use double quotes for strings.
quote-style = "double"

[tool.ruff.lint]
# 每个规则集的具体内容请参考：https://docs.astral.sh/ruff/rules/
select = [
  "YTT",
  "ASYNC",
  "S",
  "BLE",
  "B",
  "A",
  "C4",
  "T10",
  "DJ",
  "EXE",
  "FA",
  "INT",
  "ISC",
  "ICN",
  'LOG',
  'G',
  'INP',
  'PIE',
  'T20',
  'PYI',
  'PT',
  'Q',
  'RSE',
  'RET',
  'SIM',
  'SLOT',
  'TID',
  'TC',
  'FLY',
  'I',
  'C90',
  'N',
  'PERF',
  'E',
  'W',
  'F',
  'PL',
  'PLC',
  'PLE',
  'PLR',
  'PLW',
  'FURB',
  'RUF',
  'TRY',
]
# All Rule: https://beta.ruff.rs/docs/rules/
# Add `noqa: E501` manually when necessary until this issue is fixed: https://github.com/astral-sh/ruff/issues/3825
# 理论上来说，ignore 规则列表中的条目越少越好。但在实际项目中，选择性地忽略某些规则常常是必须的。
# 下面收集了常见的待忽略规则集，并将其分为两类：“推荐忽略”和“谨慎忽略”。“推荐忽略”类中所包含的规
# 则，所有项目建议默认启用。“谨慎忽略”类中的规则，项目可酌情添加。
#
# 除此处列出的规则以外，不建议随意扩充忽略规则列表。
ignore = [
  # === 推荐忽略 ===
  # pyflakes: 忽略后，允许使用 import *，仅在个别情况下搭配 __all__ 使用
  "F403",
  "F405",
  # pycodestyle: 忽略后，不检查行长，最大的每行长度直接由 ruff formatter 来保证
  "E501",
  # pycodestyle: 忽略后，不再对多行字符串的版权头信息报错， 假如将其批量调整成普通 # 号注释后可解
  "E402",
  # flake8-comprehensions: 忽略后，允许使用 dict() 函数来构建字典对象
  "C408",
  # flake8-bugbear: 忽略后，允许对字面量属性名使用 getattr/setattr 函数
  "B009",
  "B010",
  # flake8-bugbear: 忽略后，允许在 except 语句块中使用裸的 raise 语句，不要求必须使用 raise ... from
  "B904",
  # pylint：忽略后，允许定义超过 5 个参数的函数
  "PLR0913",
  # pylint：忽略后，允许直接和 magic value 字面量做比较，因为并非所有情况都适合抽象常量
  "PLR2004",
  # flake8-return: 忽略后，允许在 return 前定义一个临时变量，这有时对可读性有帮助
  "RET504",
  # flake8-return: 忽略后，允许使用非必须的分支包裹 return/raise 语句，这有时对可读性有帮助
  "RET505",
  "RET506",
  # pep8-naming: 忽略后，不强制 class 内的变量使用蛇形命名，因为部分情况下驼峰命名更契合上下文
  "N815",
  # pep8-naming: 忽略后，允许使用短名字作为导入时的别名
  "N817",
  # pep8-naming: 忽略后，不强制要求异常类的名字必须以 Error 结尾
  "N818",
  # perflint: 忽略后，不强制要求一定用推导式替代 for 循环，因为有时循环的可读性更好
  "PERF401",
  # perflint: 忽略后，允许在循环中使用 try except 代码块，因为这对性能影响微乎其微，有时可读性更好
  "PERF203",
  # tryceratops: 忽略后，允许抛出异常时，使用较长的字符串作为异常信息，可能会降低异常的可使用性
  "TRY003",
  # tryceratops: 忽略后，允许在一个 try block 内部重复 raise 而不需要抽象为函数
  "TRY301",
  # flake8-simplify: 忽略后，允许使用 exception: pass 语句，不要求必须用 contextlib.suppress 替换
  "SIM105",
  # flake8-simplify: 忽略后，不强制要求用三元表达式替换普通的短 if-else 语句
  "SIM108",
  # flake8-pytest-style：忽略后，允许 fixture 显式指定 scope="function"
  "PT003",
  # flake8-pytest-style：忽略后，不再关注 @pytest.fixture 无参数时是否需要加括号
  "PT001",
  # flake8-pytest-style：忽略后，不在关注 @pytest.mark.<marker> 无参数时是否需要加括号
  "PT023",
  # flake8-bandit：忽略后，允许使用 assert 语句
  "S101",
  # flake8-bandit：忽略后，允许使用 random 模块生成随机数（主要不要用在安全场景中）
  "S311",
  # flake8-bandit：忽略后，允许把硬编码的字符串赋值给“密码“类变量（测试文件常用）
  "S105",
  "S106",
  "S107",
  # TODO flake8-bandit：忽略后，允许代码中使用 "/tmp/filename.txt" 这样的硬编码临时文件路径
  # "S108",
  # TODO flake8-bandit：忽略后，允许使用 "0.0.0.0" IP 地址，易被误报为绑定不安全的地址
  # "S104",
  # TODO flake8-bandit：忽略后，对于开启了 shell=False，但输入命令为变量的常规 Popen 调用不再报错，
  # 人为确保输入命令安全（本规则经常产生假阳性）。
  # "S603",
  # flake8-django: 忽略后，允许模型的 StringField 使用 null=True
  "DJ001",
  # flake8-django: 忽略后，不要求 Django 模型必须实现 __str__ 方法
  "DJ008",
  # flake8-implicit-str-concat: 忽略后，在可隐式连接字符串的场景中，仍可显式使用 +
  "ISC003",
  # Ruff-specific rules：忽略后，不要检查 docstring、注释等是否包含中文全角字符
  "RUF001",
  "RUF002",
  "RUF003",
  # Ruff-specific rules：忽略后，允许使用 + 来拼接 list 而不是强制使用解包语法
  "RUF005",
  # Ruff-specific rules：忽略后，允许 class 使用可变类型作为属性（定义 ViewSet 时常见）
  "RUF012",

  # === 谨慎忽略（全新项目不建议忽略） ===
  # pep8-naming: 忽略后，不强制 class 必须使用驼峰命名，部分单元测试代码中用下划线起名可能更方便
  "N801",
  # flake8-logging-format: 忽略后，允许在打印日志时使用 .format() 方法，可能降低性能
  "G001",
  # flake8-logging-format: 忽略后，允许在打印日志时使用 f-string 表达式，更可读但可能降低性能
  "G004",
  # pylint: 忽略后，允许使用 global 关键字修改全局变量
  "PLW0603",
  # pylint: 忽略后，允许在函数体内使用 import 语句
  "PLC0415",
  # flake8-builtins: 忽略后，允许函数使用 type 等内置名字作为参数名
  "A002",
]
[tool.ruff.lint.per-file-ignores]
"manage.py" = ["INP001"]
"**/tests/**.py" = ["PLR2004", "S101"]

[tool.ruff.lint.mccabe]
# Unlike Flake8, default to a complexity level of 10.
max-complexity = 10

[tool.ruff.lint.isort]
relative-imports-order = "closest-to-furthest"
# 总是显式制定 import section 的顺序
section-order = [
  "future",
  "standard-library",
  "third-party",
  "first-party",
  "local-folder",
]
# 添加那些不能被默认识别的 first party 的模块名
known-first-party=["bkuser", "tests"]

[tool.importlinter]
root_package = "bkuser"

# 分层
[[tool.importlinter.contracts]]
name = "Layers contract"
type = "layers"
layers = [
    "bkuser.apis | bkuser.auth | bkuser.monitoring",
    "bkuser.biz",
    "bkuser.apps",
    "bkuser.plugins",
    "bkuser.component",
    "bkuser.common",
    "bkuser.utils",
]
ignore_imports = [
    "bkuser.apps.tenant.management.commands.* -> bkuser.biz.tenant",
]

# apps 分层
[[tool.importlinter.contracts]]
name = "Apps Layers contract"
type = "layers"
layers = [
    "bkuser.apps.sync | bkuser.apps.permission",
    "bkuser.apps.notification",
    "bkuser.apps.tenant",
    "bkuser.apps.idp",
    "bkuser.apps.data_source",
]

# apos.sync 分层
[[tool.importlinter.contracts]]
name = "Apps sync Layers contract"
type = "layers"
layers = [
    "bkuser.apps.sync.periodic_tasks",
    "bkuser.apps.sync.managers",
    "bkuser.apps.sync.tasks",
    "bkuser.apps.sync.runners",
    "bkuser.apps.sync.syncers",
    "bkuser.apps.sync.models",
]

# biz 分层
[[tool.importlinter.contracts]]
name = "Biz Layers contract"
type = "layers"
layers = [
    "bkuser.biz.tenant",
    "bkuser.biz.data_source | bkuser.biz.organization | bkuser.biz.exporters",
    "bkuser.biz.validators",
]

# apis 独立模块
[[tool.importlinter.contracts]]
name = "Apis Independence contract"
type = "independence"
modules = [
    "bkuser.apis.login",
    "bkuser.apis.open_v2",
    "bkuser.apis.web",
]

# apis.web 独立模块
[[tool.importlinter.contracts]]
name = "Apis Web Independence contract"
type = "independence"
modules = [
    "bkuser.apis.web.basic",
    "bkuser.apis.web.data_source",
    "bkuser.apis.web.organization",
    "bkuser.apis.web.platform_management",
]
ignore_imports = [
    "bkuser.apis.web.*.views -> bkuser.apis.web.*.serializers",
]
