swagger: "2.0"
basePath: /
info:
  version: "2.0"
  title: API Gateway Resources
  description: ""
schemes:
  - http
paths:
  /api/v3/open/frontend/tenant/users/{bk_username}/display_name/:
    get:
      operationId: retrieve_user_display_name
      description: 查询用户展示名
      tags: []
      responses:
        default:
          description: ""
      x-bk-apigateway-resource:
        isPublic: true
        allowApplyPermission: false
        matchSubpath: false
        backend:
          name: default
          method: get
          path: /api/v3/open/frontend/tenant/users/{bk_username}/display_name/
          matchSubpath: false
          timeout: 0
        pluginConfigs: []
        authConfig:
          userVerifiedRequired: true
          appVerifiedRequired: false
          resourcePermissionRequired: false
        descriptionEn: Query user's display_name

  /api/v3/open/frontend/tenant/users/-/display_names/:
    get:
      operationId: batch_query_user_display_name
      description: 批量查询用户展示名
      tags: []
      responses:
        default:
          description: ""
      x-bk-apigateway-resource:
        isPublic: true
        allowApplyPermission: false
        matchSubpath: false
        backend:
          name: default
          method: get
          path: /api/v3/open/frontend/tenant/users/-/display_names/
          matchSubpath: false
          timeout: 0
        pluginConfigs: []
        authConfig:
          userVerifiedRequired: true
          appVerifiedRequired: false
          resourcePermissionRequired: false
        descriptionEn: Batch query user's display_name

  /:
    options:
      operationId: cors_options
      description: CORS 预检请求
      tags: []
      responses:
        default:
          description: ""
      x-bk-apigateway-resource:
        isPublic: false
        allowApplyPermission: false
        matchSubpath: true
        backend:
          name: default
          method: options
          path: /
          matchSubpath: true
          timeout: 0
        pluginConfigs: []
        authConfig:
          userVerifiedRequired: false
          appVerifiedRequired: true
          resourcePermissionRequired: true
        descriptionEn: CORS preflight request
