# Generated by Django 4.2.23 on 2026-07-28 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasourcesynctask',
            name='data_source_name',
            field=models.CharField(default='', max_length=64, verbose_name='数据源名称快照'),
        ),
        migrations.AddField(
            model_name='tenantsynctask',
            name='data_source_name',
            field=models.CharField(default='', max_length=64, verbose_name='数据源名称快照'),
        ),
    ]
