# Generated by Django 3.2.20 on 2023-09-19 12:17

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasourcesynctask',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='tenantsynctask',
            name='start_time',
        ),
        migrations.AddField(
            model_name='datasourcesynctask',
            name='extra',
            field=models.JSONField(default=dict, verbose_name='扩展信息'),
        ),
        migrations.AddField(
            model_name='datasourcesynctask',
            name='start_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='任务开始时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tenantsynctask',
            name='extra',
            field=models.JSONField(default=dict, verbose_name='扩展信息'),
        ),
        migrations.AddField(
            model_name='tenantsynctask',
            name='start_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='任务开始时间'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='datasourcesynctask',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(0), verbose_name='任务持续时间'),
        ),
        migrations.AlterField(
            model_name='datasourcesynctask',
            name='trigger',
            field=models.CharField(choices=[('crontab', '定时任务'), ('manual', '手动'), ('signal', '信号触发')], max_length=32, verbose_name='触发方式'),
        ),
        migrations.AlterField(
            model_name='tenantsynctask',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(0), verbose_name='任务持续时间'),
        ),
        migrations.AlterField(
            model_name='tenantsynctask',
            name='tenant_id',
            field=models.CharField(max_length=128, verbose_name='租户 ID'),
        ),
        migrations.AlterField(
            model_name='tenantsynctask',
            name='trigger',
            field=models.CharField(choices=[('crontab', '定时任务'), ('manual', '手动'), ('signal', '信号触发')], max_length=32, verbose_name='触发方式'),
        ),
    ]
