# Generated by Django 3.2.20 on 2023-09-19 01:59

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0002_auto_20230913_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasourcesynctask',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='tenantsynctask',
            name='start_time',
        ),
        migrations.AddField(
            model_name='datasourcesynctask',
            name='start_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='任务开始时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tenantsynctask',
            name='start_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='任务开始时间'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='datasourcesynctask',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(0), verbose_name='任务持续时间'),
        ),
        migrations.AlterField(
            model_name='tenantsynctask',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(0), verbose_name='任务持续时间'),
        ),
    ]
