# Generated by Django 3.2.20 on 2024-05-15 03:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sync", "0002_tenantsynctask_summary"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tenantdepartmentchangelog",
            name="department_id",
        ),
        migrations.RemoveField(
            model_name="tenantuserchangelog",
            name="user_id",
        ),
        migrations.AddField(
            model_name="tenantdepartmentchangelog",
            name="data_source_department_id",
            field=models.IntegerField(default=0, verbose_name="数据源部门 ID"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tenantdepartmentchangelog",
            name="tenant_department_id",
            field=models.IntegerField(default=0, verbose_name="租户部门 ID"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tenantsynctask",
            name="data_source_sync_task_id",
            field=models.IntegerField(default=0, verbose_name="数据源同步任务 ID"),
        ),
        migrations.AddField(
            model_name="tenantuserchangelog",
            name="data_source_user_id",
            field=models.IntegerField(default=0, verbose_name="数据源用户 ID"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tenantuserchangelog",
            name="tenant_user_id",
            field=models.CharField(default="", max_length=64, verbose_name="租户用户 ID"),
            preserve_default=False,
        ),
    ]
