# Generated by Django 3.2.20 on 2023-09-17 12:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0002_auto_20230913_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasourcesynctask',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(0), verbose_name='任务持续时间'),
        ),
        migrations.AlterField(
            model_name='datasourcesynctask',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='任务开始时间'),
        ),
        migrations.AlterField(
            model_name='tenantsynctask',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(0), verbose_name='任务持续时间'),
        ),
        migrations.AlterField(
            model_name='tenantsynctask',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='任务开始时间'),
        ),
    ]
