# Generated by Django 3.2.20 on 2023-10-24 11:03

import bkuser.utils.uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0002_auto_20230919_2017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenantsyncstep',
            name='task',
        ),
        migrations.RemoveField(
            model_name='tenantdepartmentchangelog',
            name='department_name',
        ),
        migrations.RemoveField(
            model_name='tenantuserchangelog',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='tenantuserchangelog',
            name='username',
        ),
        migrations.AddField(
            model_name='datasourcesynctask',
            name='has_warning',
            field=models.BooleanField(default=False, verbose_name='任务执行是否有警告'),
        ),
        migrations.AddField(
            model_name='datasourcesynctask',
            name='logs',
            field=models.TextField(default='', verbose_name='任务日志'),
        ),
        migrations.AddField(
            model_name='tenantsynctask',
            name='has_warning',
            field=models.BooleanField(default=False, verbose_name='任务执行是否有警告'),
        ),
        migrations.AddField(
            model_name='tenantsynctask',
            name='logs',
            field=models.TextField(default='', verbose_name='任务日志'),
        ),
        migrations.AlterField(
            model_name='datasourcedepartmentchangelog',
            name='id',
            field=models.UUIDField(default=bkuser.utils.uuid.generate_uuid, primary_key=True, serialize=False, verbose_name='变更日志 ID'),
        ),
        migrations.AlterField(
            model_name='datasourceuserchangelog',
            name='id',
            field=models.UUIDField(default=bkuser.utils.uuid.generate_uuid, primary_key=True, serialize=False, verbose_name='变更日志 ID'),
        ),
        migrations.AlterField(
            model_name='tenantdepartmentchangelog',
            name='id',
            field=models.UUIDField(default=bkuser.utils.uuid.generate_uuid, primary_key=True, serialize=False, verbose_name='变更日志 ID'),
        ),
        migrations.AlterField(
            model_name='tenantdepartmentchangelog',
            name='tenant_id',
            field=models.CharField(max_length=128, verbose_name='租户 ID'),
        ),
        migrations.AlterField(
            model_name='tenantuserchangelog',
            name='id',
            field=models.UUIDField(default=bkuser.utils.uuid.generate_uuid, primary_key=True, serialize=False, verbose_name='变更日志 ID'),
        ),
        migrations.AlterField(
            model_name='tenantuserchangelog',
            name='tenant_id',
            field=models.CharField(max_length=128, verbose_name='租户 ID'),
        ),
        migrations.DeleteModel(
            name='DataSourceSyncStep',
        ),
        migrations.DeleteModel(
            name='TenantSyncStep',
        ),
    ]
