# Generated by Django 3.2.20 on 2023-10-25 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0005_builtin_user_fields'),
        ('data_source', '0008_auto_20231024_0940'),
        ('sync', '0003_auto_20231024_1903'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datasourcesynctask',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='tenantsynctask',
            options={'ordering': ['-id']},
        ),
        migrations.RenameField(
            model_name='datasourcesynctask',
            old_name='extra',
            new_name='extras',
        ),
        migrations.RenameField(
            model_name='tenantsynctask',
            old_name='extra',
            new_name='extras',
        ),
        migrations.RemoveField(
            model_name='datasourcedepartmentchangelog',
            name='data_source_id',
        ),
        migrations.RemoveField(
            model_name='datasourcesynctask',
            name='data_source_id',
        ),
        migrations.RemoveField(
            model_name='datasourceuserchangelog',
            name='data_source_id',
        ),
        migrations.RemoveField(
            model_name='tenantdepartmentchangelog',
            name='data_source_id',
        ),
        migrations.RemoveField(
            model_name='tenantdepartmentchangelog',
            name='tenant_id',
        ),
        migrations.RemoveField(
            model_name='tenantsynctask',
            name='data_source_id',
        ),
        migrations.RemoveField(
            model_name='tenantsynctask',
            name='tenant_id',
        ),
        migrations.RemoveField(
            model_name='tenantuserchangelog',
            name='data_source_id',
        ),
        migrations.RemoveField(
            model_name='tenantuserchangelog',
            name='tenant_id',
        ),
        migrations.AddField(
            model_name='datasourcedepartmentchangelog',
            name='data_source',
            field=models.ForeignKey(db_constraint=False, default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='data_source.datasource'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datasourcesynctask',
            name='data_source',
            field=models.ForeignKey(db_constraint=False, default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='data_source.datasource'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datasourceuserchangelog',
            name='data_source',
            field=models.ForeignKey(db_constraint=False, default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='data_source.datasource'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tenantdepartmentchangelog',
            name='data_source',
            field=models.ForeignKey(db_constraint=False, default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='data_source.datasource'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tenantdepartmentchangelog',
            name='tenant',
            field=models.ForeignKey(db_constraint=False, default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='tenant.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tenantsynctask',
            name='data_source',
            field=models.ForeignKey(db_constraint=False, default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='data_source.datasource'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tenantsynctask',
            name='tenant',
            field=models.ForeignKey(db_constraint=False, default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='tenant.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tenantuserchangelog',
            name='data_source',
            field=models.ForeignKey(db_constraint=False, default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='data_source.datasource'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tenantuserchangelog',
            name='tenant',
            field=models.ForeignKey(db_constraint=False, default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='tenant.tenant'),
            preserve_default=False,
        ),
    ]
