# coding: utf-8

"""
    蓝鲸用户管理 API

    蓝鲸用户管理后台服务 API  # noqa: E501

    OpenAPI spec version: v2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class DepartmentAddProfiles(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'profile_id_list': 'list[int]'
    }

    attribute_map = {
        'profile_id_list': 'profile_id_list'
    }

    def __init__(self, profile_id_list=None):  # noqa: E501
        """DepartmentAddProfiles - a model defined in Swagger"""  # noqa: E501
        self._profile_id_list = None
        self.discriminator = None
        self.profile_id_list = profile_id_list

    @property
    def profile_id_list(self):
        """Gets the profile_id_list of this DepartmentAddProfiles.  # noqa: E501


        :return: The profile_id_list of this DepartmentAddProfiles.  # noqa: E501
        :rtype: list[int]
        """
        return self._profile_id_list

    @profile_id_list.setter
    def profile_id_list(self, profile_id_list):
        """Sets the profile_id_list of this DepartmentAddProfiles.


        :param profile_id_list: The profile_id_list of this DepartmentAddProfiles.  # noqa: E501
        :type: list[int]
        """
        if profile_id_list is None:
            raise ValueError("Invalid value for `profile_id_list`, must not be `None`")  # noqa: E501

        self._profile_id_list = profile_id_list

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DepartmentAddProfiles, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DepartmentAddProfiles):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
