# coding: utf-8

"""
    蓝鲸用户管理 API

    蓝鲸用户管理后台服务 API  # noqa: E501

    OpenAPI spec version: v2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class LoginBatchQuery(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'username_list': 'list[str]',
        'is_complete': 'bool'
    }

    attribute_map = {
        'username_list': 'username_list',
        'is_complete': 'is_complete'
    }

    def __init__(self, username_list=None, is_complete=None):  # noqa: E501
        """LoginBatchQuery - a model defined in Swagger"""  # noqa: E501
        self._username_list = None
        self._is_complete = None
        self.discriminator = None
        if username_list is not None:
            self.username_list = username_list
        if is_complete is not None:
            self.is_complete = is_complete

    @property
    def username_list(self):
        """Gets the username_list of this LoginBatchQuery.  # noqa: E501


        :return: The username_list of this LoginBatchQuery.  # noqa: E501
        :rtype: list[str]
        """
        return self._username_list

    @username_list.setter
    def username_list(self, username_list):
        """Sets the username_list of this LoginBatchQuery.


        :param username_list: The username_list of this LoginBatchQuery.  # noqa: E501
        :type: list[str]
        """

        self._username_list = username_list

    @property
    def is_complete(self):
        """Gets the is_complete of this LoginBatchQuery.  # noqa: E501


        :return: The is_complete of this LoginBatchQuery.  # noqa: E501
        :rtype: bool
        """
        return self._is_complete

    @is_complete.setter
    def is_complete(self, is_complete):
        """Sets the is_complete of this LoginBatchQuery.


        :param is_complete: The is_complete of this LoginBatchQuery.  # noqa: E501
        :type: bool
        """

        self._is_complete = is_complete

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(LoginBatchQuery, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, LoginBatchQuery):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
