# coding: utf-8

"""
    蓝鲸用户管理 API

    蓝鲸用户管理后台服务 API  # noqa: E501

    OpenAPI spec version: v2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class ProfileLogin(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'username': 'str',
        'password': 'str',
        'domain': 'str'
    }

    attribute_map = {
        'username': 'username',
        'password': 'password',
        'domain': 'domain'
    }

    def __init__(self, username=None, password=None, domain=None):  # noqa: E501
        """ProfileLogin - a model defined in Swagger"""  # noqa: E501
        self._username = None
        self._password = None
        self._domain = None
        self.discriminator = None
        self.username = username
        self.password = password
        if domain is not None:
            self.domain = domain

    @property
    def username(self):
        """Gets the username of this ProfileLogin.  # noqa: E501

        用户名  # noqa: E501

        :return: The username of this ProfileLogin.  # noqa: E501
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username):
        """Sets the username of this ProfileLogin.

        用户名  # noqa: E501

        :param username: The username of this ProfileLogin.  # noqa: E501
        :type: str
        """
        if username is None:
            raise ValueError("Invalid value for `username`, must not be `None`")  # noqa: E501

        self._username = username

    @property
    def password(self):
        """Gets the password of this ProfileLogin.  # noqa: E501

        用户密码  # noqa: E501

        :return: The password of this ProfileLogin.  # noqa: E501
        :rtype: str
        """
        return self._password

    @password.setter
    def password(self, password):
        """Sets the password of this ProfileLogin.

        用户密码  # noqa: E501

        :param password: The password of this ProfileLogin.  # noqa: E501
        :type: str
        """
        if password is None:
            raise ValueError("Invalid value for `password`, must not be `None`")  # noqa: E501

        self._password = password

    @property
    def domain(self):
        """Gets the domain of this ProfileLogin.  # noqa: E501

        用户所属目录 domain，当登录用户不属于默认目录时必填  # noqa: E501

        :return: The domain of this ProfileLogin.  # noqa: E501
        :rtype: str
        """
        return self._domain

    @domain.setter
    def domain(self, domain):
        """Sets the domain of this ProfileLogin.

        用户所属目录 domain，当登录用户不属于默认目录时必填  # noqa: E501

        :param domain: The domain of this ProfileLogin.  # noqa: E501
        :type: str
        """

        self._domain = domain

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ProfileLogin, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ProfileLogin):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
