# Generated by Django 3.2.20 on 2023-08-07 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False, verbose_name='租户唯一标识')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='租户名称')),
                ('logo', models.TextField(blank=True, default='', null=True, verbose_name='Logo')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否默认租户')),
                ('feature_flags', models.JSONField(default=dict, verbose_name='租户特性标志集')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TenantManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_user_id', models.CharField(db_index=True, max_length=128, verbose_name='租户用户 ID')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenant.tenant')),
            ],
            options={
                'unique_together': {('tenant', 'tenant_user_id')},
            },
        ),
    ]
