# Generated by Django 3.2.20 on 2023-07-18 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256, verbose_name='数据源名称')),
                ('code', models.CharField(max_length=256)),
                ('status', models.CharField(max_length=256)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DataSourceUser',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('data_source_id', models.CharField(max_length=256)),
                ('username', models.CharField(max_length=255, verbose_name='用户名')),
                ('display_name', models.CharField(max_length=256)),
                ('email', models.EmailField(blank=True, default='', max_length=255, null=True, verbose_name='邮箱')),
                ('telephone', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='手机号码')),
                ('logo', models.TextField(max_length=256)),
                ('staff_status', models.CharField(max_length=256)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='租户名称')),
                ('logo', models.TextField(blank=True, null=True, verbose_name='base64化的logo图片')),
                ('is_default', models.BooleanField(default=False, verbose_name='默认租户')),
                ('enabled_user_count_display', models.BooleanField(default=False, verbose_name='使能可查看用户数量')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TenantDataSourceBinding',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('tenant_id', models.IntegerField()),
                ('data_source_id', models.CharField(max_length=256)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TenantManager',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('tenant_user_id', models.CharField(max_length=256)),
                ('tenant_id', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TenantUser',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=256, verbose_name='数据源username')),
                ('display_name', models.CharField(max_length=256)),
                ('logo', models.TextField(max_length=256)),
                ('is_default', models.BooleanField(default=False)),
                ('data_source_user_id', models.IntegerField(verbose_name='逻辑外键：数据源用户id')),
                ('tenant_id', models.CharField(max_length=256, verbose_name='逻辑外键：租户ID')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
