# Generated by Django 3.2.20 on 2023-11-13 09:56
from django.db import migrations


def forwards_func(apps, schema_editor):
    """初始化用户内置字段"""

    UserBuiltinField = apps.get_model("tenant", "UserBuiltinField")
    fields = [
        UserBuiltinField(
            name="username",
            display_name="用户名",
            data_type="string",
            required=True,
            unique=True,
        ),
        UserBuiltinField(
            name="full_name",
            display_name="姓名",
            data_type="string",
            required=True,
            unique=False,
        ),
        UserBuiltinField(
            name="email",
            display_name="邮箱",
            data_type="string",
            required=False,
            unique=False,
        ),
        UserBuiltinField(
            name="phone",
            display_name="手机号",
            data_type="string",
            required=False,
            unique=False,
        ),
        UserBuiltinField(
            name="phone_country_code",
            display_name="手机国际区号",
            data_type="string",
            required=False,
            unique=False,
        ),
    ]
    UserBuiltinField.objects.bulk_create(fields)


class Migration(migrations.Migration):
    dependencies = [
        ("tenant", "0001_initial"),
    ]

    operations = [migrations.RunPython(forwards_func)]
