# Generated by Django 3.2.20 on 2023-11-13 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0002_init_builtin_user_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantuser',
            name='wx_openid',
            field=models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='微信公众号 用户OpenID'),
        ),
        migrations.CreateModel(
            name='TenantUserValidityPeriodConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.CharField(blank=True, max_length=128, null=True)),
                ('updater', models.CharField(blank=True, max_length=128, null=True)),
                ('enabled', models.BooleanField(default=True, verbose_name='是否启用账户有效期')),
                ('validity_period', models.IntegerField(default=-1, verbose_name='有效期(单位：天)')),
                ('remind_before_expire', models.JSONField(default=list, verbose_name='临X天过期发送提醒(单位：天)')),
                ('enabled_notification_methods', models.JSONField(default=list, verbose_name='通知方式')),
                ('notification_templates', models.JSONField(default=list, verbose_name='通知模板')),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tenant.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
