# Generated by Django 3.2.20 on 2023-09-14 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0002_tenantusercustomfield_userbuiltinfield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenantusercustomfield',
            name='order',
        ),
        migrations.AlterField(
            model_name='tenantusercustomfield',
            name='data_type',
            field=models.CharField(choices=[('string', '字符串'), ('number', '数字'), ('enum', '枚举'), ('multi_enum', '多选枚举')], max_length=32, verbose_name='数据类型'),
        ),
        migrations.AlterField(
            model_name='userbuiltinfield',
            name='data_type',
            field=models.CharField(choices=[('string', '字符串'), ('number', '数字'), ('enum', '枚举'), ('multi_enum', '多选枚举')], max_length=32, verbose_name='数据类型'),
        ),
        migrations.AlterField(
            model_name='userbuiltinfield',
            name='display_name',
            field=models.CharField(max_length=128, unique=True, verbose_name='展示用名称'),
        ),
    ]
