# Generated by Django 3.2.25 on 2024-08-27 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_source', '0002_init_builtin_data_source_plugin'),
        ('tenant', '0003_init_default_tenant'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantUserUUIDRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=128, verbose_name='用户在数据源中的唯一标识')),
                ('uuid', models.CharField(max_length=128, verbose_name='UUID')),
                ('data_source', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='data_source.datasource', unique=True)),
                ('tenant', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='tenant.tenant')),
            ],
            options={
                'unique_together': {('tenant_id', 'data_source_id', 'code')},
            },
        ),
    ]
