# Generated by Django 3.2.20 on 2023-11-29 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0003_init_default_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantusercustomfield',
            name='unique',
            field=models.BooleanField(default=False, verbose_name='是否唯一'),
        ),
        migrations.AlterField(
            model_name='tenantusercustomfield',
            name='display_name',
            field=models.CharField(max_length=128, verbose_name='字段名称'),
        ),
        migrations.AlterField(
            model_name='tenantusercustomfield',
            name='name',
            field=models.CharField(max_length=128, verbose_name='英文标识'),
        ),
    ]
