# Generated by Django 3.2.25 on 2024-08-28 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_source', '0002_init_builtin_data_source_plugin'),
        ('tenant', '0003_init_default_tenant'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantUserIDRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=128, verbose_name='用户在数据源中的唯一标识')),
                ('tenant_user_id', models.CharField(max_length=128, verbose_name='租户用户 ID')),
                ('data_source', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='data_source.datasource')),
                ('tenant', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='tenant.tenant')),
            ],
            options={
                'unique_together': {('tenant', 'data_source', 'code')},
            },
        ),
    ]
