# Generated by Django 3.2.20 on 2024-04-30 06:49

import bkuser.apps.tenant.constants
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0003_init_default_tenant'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollaborativeStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.CharField(blank=True, max_length=128, null=True)),
                ('updater', models.CharField(blank=True, max_length=128, null=True)),
                ('name', models.CharField(max_length=128, verbose_name='策略名称')),
                ('source_status', models.CharField(choices=[('enabled', '启用'), ('disabled', '禁用'), ('unconfirmed', '未确认')], default=bkuser.apps.tenant.constants.CollaborativeStrategyStatus['ENABLED'], max_length=32, verbose_name='策略状态（分享方）')),
                ('target_status', models.CharField(choices=[('enabled', '启用'), ('disabled', '禁用'), ('unconfirmed', '未确认')], default=bkuser.apps.tenant.constants.CollaborativeStrategyStatus['UNCONFIRMED'], max_length=32, verbose_name='策略状态（接受方）')),
                ('source_config', models.JSONField(default=dict, verbose_name='策略配置（分享方）')),
                ('target_config', models.JSONField(default=dict, verbose_name='策略配置（接受方）')),
                ('source_tenant', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='source_tenant', to='tenant.tenant')),
                ('target_tenant', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='target_tenant', to='tenant.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
