# Generated by Django 3.2.20 on 2023-09-14 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0003_auto_20230914_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantuser',
            name='custom_phone',
            field=models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='自定义手机号'),
        ),
    ]
