# Generated by Django 3.2.25 on 2024-07-08 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_source', '0003_auto_20240705_1119'),
        ('tenant', '0004_auto_20240508_0952'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantUserIDGenerateConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rule', models.CharField(choices=[('uuid4_hex', 'uuid4 hex'), ('username', '用户名'), ('username@domain', '用户名@域名')], default='uuid4_hex', max_length=64, verbose_name='租户用户 ID 生成规则')),
                ('domain', models.CharField(blank=True, max_length=128, null=True, unique=True, verbose_name='目标租户域名')),
                ('data_source', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='data_source.datasource', unique=True)),
                ('target_tenant', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='tenant.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
