# Generated by Django 3.2.20 on 2024-01-18 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0005_auto_20231219_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantusercustomfield',
            name='use_digit_option_id',
            field=models.BooleanField(default=False, verbose_name='是否使用数字作为选项ID'),
        ),
    ]
