# Generated by Django 3.2.20 on 2023-11-01 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0005_builtin_user_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantUserValidityPeriodConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.CharField(blank=True, max_length=128, null=True)),
                ('updater', models.CharField(blank=True, max_length=128, null=True)),
                ('enabled_validity_period', models.BooleanField(default=True, verbose_name='是否启用')),
                ('valid_time', models.IntegerField(default=-1, verbose_name='有效期(单位：天)')),
                ('remind_before_expire', models.JSONField(default=list, verbose_name='临X天过期发送提醒(单位：天)')),
                ('enabled_notification_methods', models.JSONField(default=dict, verbose_name='通知方式')),
                ('notification_templates', models.JSONField(default=dict, verbose_name='通知模板')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenant.tenant', unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
