# Generated by Django 4.2.17 on 2024-12-16 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenant", "0005_tenantdepartmentidrecord"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenantuseridgenerateconfig",
            name="rule",
            field=models.CharField(
                choices=[
                    ("nanoid", "nanoid"),
                    ("uuid4_hex", "uuid4 hex"),
                    ("username", "用户名"),
                    ("username@domain", "用户名@域名"),
                ],
                default="nanoid",
                max_length=64,
                verbose_name="租户用户 ID 生成规则",
            ),
        ),
    ]
