# Generated by Django 4.2.16 on 2024-12-26 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tenant", "0006_alter_tenantuseridgenerateconfig_rule"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userbuiltinfield",
            options={"ordering": ["id"]},
        ),
    ]
