# Generated by Django 3.2.20 on 2024-01-25 07:23

import bkuser.apps.tenant.constants
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0006_tenantusercustomfield_use_digit_option_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='creator',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='status',
            field=models.CharField(choices=[('enabled', '启用'), ('disabled', '禁用'), ('deleted', '软删除')], default=bkuser.apps.tenant.constants.TenantStatus['ENABLED'], max_length=32, verbose_name='状态'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='updater',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='tenantdepartment',
            name='status',
            field=models.CharField(choices=[('enabled', '启用'), ('disabled', '禁用')], default=bkuser.apps.tenant.constants.TenantDepartmentStatus['ENABLED'], max_length=32, verbose_name='状态'),
        ),
        migrations.AddField(
            model_name='tenantuser',
            name='status',
            field=models.CharField(choices=[('enabled', '启用'), ('disabled', '禁用'), ('expired', '已过期'), ('deleted', '软删除')], default=bkuser.apps.tenant.constants.TenantUserStatus['ENABLED'], max_length=32, verbose_name='状态'),
        ),
    ]
