# Generated by Django 3.2.20 on 2024-01-24 02:15

import bkuser.apps.tenant.constants
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0006_tenantusercustomfield_use_digit_option_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantdepartment',
            name='status',
            field=models.CharField(choices=[('enabled', '启用'), ('disabled', '禁用')], default=bkuser.apps.tenant.constants.TenantDepartmentStatus['ENABLED'], max_length=32, verbose_name='状态'),
        ),
        migrations.AddField(
            model_name='tenantuser',
            name='status',
            field=models.CharField(choices=[('enabled', '启用'), ('disabled', '禁用'), ('expired', '已过期')], default=bkuser.apps.tenant.constants.TenantUserStatus['ENABLED'], max_length=32, verbose_name='状态'),
        ),
    ]
