# Generated by Django 3.2.20 on 2023-11-06 04:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0006_tenantuservalidityperiodconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantuser',
            name='account_expired_at',
            field=models.DateField(blank=True, default=datetime.datetime(2100, 1, 1, 0, 0), null=True, verbose_name='账号过期时间'),
        ),
    ]
