# Generated by Django 3.2.20 on 2024-03-28 01:41

import bkuser.common.constants
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0007_auto_20240125_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='user_number_visible',
            field=models.BooleanField(default=True, verbose_name='人员数量是否可见'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='visible',
            field=models.BooleanField(default=True, verbose_name='租户可见性'),
        ),
        migrations.AlterField(
            model_name='tenantuser',
            name='language',
            field=models.CharField(choices=[('zh-CN', '中文'), ('en-US', '英文')], default=bkuser.common.constants.BkLanguageEnum['ZH_CN'], max_length=32, verbose_name='语言'),
        ),
    ]
