# Generated by Django 4.2.18 on 2025-04-03 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tenant", "0007_alter_userbuiltinfield_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="TenantCommonVariable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=64, verbose_name="变量名")),
                ("value", models.CharField(max_length=255, verbose_name="变量值")),
                (
                    "tenant",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenant.tenant",
                    ),
                ),
            ],
            options={
                "unique_together": {("tenant", "name")},
            },
        ),
    ]
