# Generated by Django 3.2.20 on 2024-01-25 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0008_auto_20240125_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='creator',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='updater',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
