# Generated by Django 4.2.16 on 2025-05-14 15:56

import os
from django.db import migrations, models
import django.db.models.deletion
from bkuser.apps.tenant.constants import BuiltInTenantIDEnum, \
    DEFAULT_TENANT_USER_DISPLAY_NAME_EXPRESSION_CONFIG

def forwards_func(apps, schema_editor):
    # 根据是否开启多租户模式，选择初始化展示名称表达式配置的租户（运营租户或默认租户）
    enable_mutil_tenant_mode = os.getenv("ENABLE_MUTIL_TENANT_MODE", "false").lower() == "true"
    first_tenant_id = BuiltInTenantIDEnum.SYSTEM if enable_mutil_tenant_mode else BuiltInTenantIDEnum.DEFAULT
    TenantUserDisplayNameExpressionConfig = apps.get_model("tenant", "TenantUserDisplayNameExpressionConfig")
    TenantUserDisplayNameExpressionConfig.objects.create(tenant_id=first_tenant_id, **DEFAULT_TENANT_USER_DISPLAY_NAME_EXPRESSION_CONFIG)

class Migration(migrations.Migration):

    dependencies = [
        ("tenant", "0008_tenantcommonvariable"),
    ]

    operations = [
        migrations.CreateModel(
            name="TenantUserDisplayNameExpressionConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "expression",
                    models.CharField(max_length=128, verbose_name="展示名称表达式"),
                ),
                ("fields", models.JSONField(default=dict, verbose_name="配置字段")),
                ("version", models.IntegerField(default=1, verbose_name="版本号")),
                (
                    "tenant",
                    models.OneToOneField(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenant.tenant",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RunPython(forwards_func),
    ]
