# Generated by Django 4.2.16 on 2025-06-04 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_source', '0002_init_builtin_data_source_plugin'),
        ('tenant', '0008_tenantcommonvariable'),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualUserOwnerRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data_source_user', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='data_source.datasourceuser')),
                ('owner', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='owned_virtual_users', to='tenant.tenantuser')),
                ('virtual_user', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='tenant.tenantuser')),
            ],
            options={
                'unique_together': {('owner', 'virtual_user')},
            },
        ),
        migrations.CreateModel(
            name='VirtualUserAppRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app_code', models.CharField(max_length=128, verbose_name='应用编码')),
                ('data_source_user', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='data_source.datasourceuser')),
                ('virtual_user', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='tenant.tenantuser')),
            ],
            options={
                'unique_together': {('app_code', 'virtual_user')},
            },
        ),
    ]
