# Generated by Django 4.2.16 on 2025-04-30 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tenant", "0002_init_builtin_user_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="TenantUserDisplayNameExpressionConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "expression",
                    models.CharField(max_length=128, verbose_name="展示名称表达式"),
                ),
                ("builtin_fields", models.JSONField(default=list, verbose_name="内置字段")),
                ("custom_fields", models.JSONField(default=list, verbose_name="自定义字段")),
                ("version", models.IntegerField(default=1, verbose_name="版本号")),
                (
                    "tenant",
                    models.OneToOneField(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenant.tenant",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
