# Generated by Django 4.2.16 on 2025-06-04 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0009_tenantuserdisplaynameexpressionconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualUserOwnerRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='owned_virtual_users', to='tenant.tenantuser')),
                ('tenant_user', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='tenant.tenantuser')),
            ],
            options={
                'unique_together': {('tenant_user', 'owner')},
                'index_together': {('owner', 'tenant_user')},
            },
        ),
        migrations.CreateModel(
            name='VirtualUserAppRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app_code', models.CharField(max_length=128, verbose_name='应用编码')),
                ('tenant_user', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='tenant.tenantuser')),
            ],
            options={
                'unique_together': {('tenant_user', 'app_code')},
                'index_together': {('app_code', 'tenant_user')},
            },
        ),
    ]
