# Generated by Django 4.2.23 on 2025-09-29 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0012_alter_tenantuser_time_zone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantUserBuiltinField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.CharField(blank=True, max_length=128, null=True)),
                ('updater', models.CharField(blank=True, max_length=128, null=True)),
                ('name', models.CharField(max_length=128, verbose_name='字段名称')),
                ('display_name', models.CharField(max_length=128, verbose_name='展示用名称')),
                ('data_type', models.CharField(choices=[('string', '字符串'), ('number', '数字'), ('enum', '枚举'), ('multi_enum', '多选枚举')], max_length=32, verbose_name='数据类型')),
                ('required', models.BooleanField(verbose_name='是否必填')),
                ('unique', models.BooleanField(verbose_name='是否唯一')),
                ('default', models.JSONField(default='', verbose_name='默认值')),
                ('options', models.JSONField(default=list, verbose_name='配置项')),
                ('personal_center_visible', models.BooleanField(default=False, verbose_name='是否在个人中心可见')),
                ('personal_center_editable', models.BooleanField(default=False, verbose_name='是否在个人中心可编辑')),
                ('manager_editable', models.BooleanField(default=True, verbose_name='租户管理员是否可重复编辑')),
                ('tenant', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='tenant.tenant')),
            ],
            options={
                'verbose_name': '租户内置字段配置',
                'ordering': ['id'],
                'unique_together': {('tenant', 'display_name'), ('tenant', 'name')},
            },
        ),
    ]
