# Generated by Django 3.2.25 on 2024-10-17 07:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OperationAuditRecord',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='事件 id')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.CharField(blank=True, max_length=128, null=True)),
                ('updater', models.CharField(blank=True, max_length=128, null=True)),
                ('operation_target', models.CharField(max_length=32, verbose_name='操作对象')),
                ('operation_type', models.CharField(max_length=32, verbose_name='操作类型')),
                ('tenant_id', models.CharField(max_length=32, verbose_name='操作对象所属的租户 id')),
                ('data_change', models.JSONField(blank=True, max_length=32, null=True, verbose_name='操作数据变更')),
                ('data_source_id', models.CharField(blank=True, max_length=32, null=True, verbose_name='操作对象所属的数据源 id')),
                ('extras', models.JSONField(blank=True, null=True, verbose_name='操作额外信息')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
