# Generated by Django 3.2.25 on 2024-10-14 06:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OperationAuditRecord',
            fields=[
                ('event_id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='事件 id')),
                ('operator', models.CharField(max_length=32, verbose_name='操作用户')),
                ('ip', models.CharField(blank=True, max_length=32, null=True, verbose_name='来源 ip')),
                ('operate_time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='操作时间')),
                ('target', models.CharField(choices=[('data_source', '数据源'), ('idp', 'IDP（认证源）'), ('user', '用户'), ('organization', '组织'), ('platform_management', '平台管理'), ('tenant', '租户'), ('virtual_user', '虚拟用户')], max_length=32, verbose_name='操作对象')),
                ('operation', models.CharField(choices=[('create_data_source', '创建数据源'), ('modify_data_source', '修改数据源'), ('delete_data_source', '删除数据源'), ('sync_data_source', '同步数据源'), ('import_data_source', '导入数据源'), ('create_idp', '创建 IDP（认证源）'), ('modify_idp', '修改 IDP（认证源）'), ('modify_idp_status', '修改 IDP（认证源）状态'), ('create_user', '创建用户'), ('modify_user', '修改用户'), ('delete_user', '删除用户'), ('modify_department_user_relations', '修改用户所属部门'), ('modify_user_status', '修改用户状态'), ('modify_account_expired_at', '修改账户过期时间'), ('modify_leaders', '修改用户上级'), ('modify_user_password', '重置用户密码'), ('modify_email', '修改邮箱'), ('modify_phone', '修改电话号码'), ('send_email_verification_code', '发送邮箱验证码'), ('send_phone_verification_code', '发送手机验证码'), ('create_organization', '创建组织'), ('modify_organization', '修改组织'), ('delete_organization', '删除组织'), ('modify_parent_organization', '修改上级组织'), ('create_tenant', '创建租户'), ('modify_tenant', '修改租户'), ('delete_tenant', '删除租户'), ('modify_tenant_status', '修改租户状态'), ('create_real_manager', '创建实名管理员'), ('delete_real_manager', '删除实名管理员'), ('modify_validity_period_config', '修改租户账户有效期配置'), ('create_virtual_user', '创建虚拟用户'), ('modify_virtual_user', '修改虚拟用户'), ('delete_virtual_user', '删除虚拟用户')], max_length=32, verbose_name='操作类型')),
                ('data_before', models.JSONField(blank=True, null=True, verbose_name='操作前的数据')),
                ('data_after', models.JSONField(blank=True, null=True, verbose_name='操作后的数据')),
                ('instance', models.JSONField(blank=True, null=True, verbose_name='操作对象实例')),
            ],
            options={
                'ordering': ['-operate_time'],
            },
        ),
    ]
