# -*- coding: utf-8 -*-
"""
TencentBlueKing is pleased to support the open source community by making 蓝鲸智云-用户管理(Bk-User) available.
Copyright (C) 2017-2021 THL A29 Limited, a Tencent company. All rights reserved.
Licensed under the MIT License (the "License"); you may not use this file except in compliance with the License.
You may obtain a copy of the License at http://opensource.org/licenses/MIT
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
specific language governing permissions and limitations under the License.
"""
# Generated by Django 1.11.23 on 2019-11-04 15:35
from __future__ import unicode_literals

import django.db.models.deletion
import jsonfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("categories", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Setting",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                ("update_time", models.DateTimeField(auto_now=True)),
                ("value", jsonfield.fields.JSONField(default={}, verbose_name="配置内容")),
                ("enable", models.BooleanField(default=True)),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to="categories.ProfileCategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "配置表",
                "verbose_name_plural": "配置表",
            },
        ),
        migrations.CreateModel(
            name="SettingMeta",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                ("update_time", models.DateTimeField(auto_now=True)),
                ("key", models.CharField(max_length=64, verbose_name="配置键")),
                ("enable", models.BooleanField(default=True)),
                ("example", jsonfield.fields.JSONField(default="", verbose_name="示例")),
                ("default", jsonfield.fields.JSONField(default="", verbose_name="默认值")),
                ("choices", jsonfield.fields.JSONField(default=[], verbose_name="可选值")),
                ("required", models.BooleanField(default=False, verbose_name="是否必要")),
                (
                    "namespace",
                    models.CharField(
                        choices=[
                            ("general", "通用"),
                            ("password", "密码"),
                            ("connection", "连接"),
                            ("fields", "连接"),
                        ],
                        db_index=True,
                        default="general",
                        max_length=32,
                        verbose_name="命名空间",
                    ),
                ),
                (
                    "region",
                    models.CharField(default="default", max_length=32, verbose_name="领域"),
                ),
                (
                    "category_type",
                    models.CharField(
                        choices=[
                            ("local", "本地目录"),
                            ("mad", "Microsoft Active Directory"),
                            ("ldap", "LDAP"),
                        ],
                        max_length=32,
                        verbose_name="类型",
                    ),
                ),
            ],
            options={
                "verbose_name": "配置元信息表",
                "verbose_name_plural": "配置元信息表",
            },
        ),
        migrations.AlterUniqueTogether(
            name="settingmeta",
            unique_together=set([("key", "namespace", "category_type")]),
        ),
        migrations.AddField(
            model_name="setting",
            name="meta",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="instances",
                to="user_settings.SettingMeta",
            ),
        ),
    ]
