# -*- coding: utf-8 -*-
"""
TencentBlueKing is pleased to support the open source community by making 蓝鲸智云-用户管理(Bk-User) available.
Copyright (C) 2017-2021 THL A29 Limited, a Tencent company. All rights reserved.
Licensed under the MIT License (the "License"); you may not use this file except in compliance with the License.
You may obtain a copy of the License at http://opensource.org/licenses/MIT
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
specific language governing permissions and limitations under the License.
"""
# Generated by Django 3.2 on 2021-04-13 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_settings", "0007_auto_20210703_2020"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="setting",
            options={
                "ordering": ["-create_time"],
                "verbose_name": "配置表",
                "verbose_name_plural": "配置表",
            },
        ),
        migrations.AlterModelOptions(
            name="settingmeta",
            options={
                "ordering": ["-create_time"],
                "verbose_name": "配置元信息表",
                "verbose_name_plural": "配置元信息表",
            },
        ),
        migrations.AlterField(
            model_name="settingmeta",
            name="category_type",
            field=models.CharField(
                choices=[
                    ("local", "本地目录"),
                    ("mad", "Microsoft Active Directory"),
                    ("ldap", "OpenLDAP"),
                    ("custom", "自定义目录"),
                ],
                max_length=32,
                verbose_name="类型",
            ),
        ),
    ]
