# Generated by Django 3.2.5 on 2021-12-01 08:01

from django.db import migrations
from django.conf import settings

from bkuser_core.categories.constants import CategoryType
from bkuser_core.user_settings.constants import SettingsEnableNamespaces


def forwards_func(apps, schema_editor):
    """增加配置项"""
    SettingMeta = apps.get_model("user_settings", "SettingMeta")
    meta = SettingMeta.objects.create(
        namespace=SettingsEnableNamespaces.PASSWORD.value,
        category_type=CategoryType.LOCAL.value,
        required=False,
        **dict(
            key="max_password_history",
            example=settings.DEFAULT_MAX_PASSWORD_HISTORY,
            default=settings.DEFAULT_MAX_PASSWORD_HISTORY,
        )
    )
    ProfileCategory = apps.get_model("categories", "ProfileCategory")
    Setting = apps.get_model("user_settings", "Setting")

    for category in ProfileCategory.objects.filter(type=CategoryType.LOCAL.value):
        Setting.objects.get_or_create(
            category=category,
            meta=meta,
            value=meta.default,
        )


def backwards_func(apps, schema_editor):
    SettingMeta = apps.get_model("user_settings", "SettingMeta")
    meta = SettingMeta.objects.get(
        namespace=SettingsEnableNamespaces.PASSWORD.value,
        category_type=CategoryType.LOCAL.value,
        key="user_member_of",
    )
    Setting = apps.get_model("user_settings", "Setting")
    Setting.objects.filter(category__type=CategoryType.LOCAL.value, meta=meta).delete()
    meta.delete()


class Migration(migrations.Migration):

    dependencies = [
        ("user_settings", "0009_alter_settingmeta_category_type"),
    ]

    operations = [migrations.RunPython(forwards_func, backwards_func)]
