# Generated by Django 3.2.5 on 2022-02-23 03:08

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user_settings', '0011_alter_extend_fields_connection_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingmeta',
            name='default',
            field=jsonfield.fields.JSONField(default=None, verbose_name='默认值'),
        ),
        migrations.AlterField(
            model_name='settingmeta',
            name='namespace',
            field=models.CharField(
                choices=[
                    ('general', '通用'),
                    ('password', '密码'),
                    ('connection', '连接'),
                    ('fields', '连接'),
                    ('notification', '通知')],
                db_index=True,
                default='general',
                max_length=32,
                verbose_name='命名空间'),
        ),
    ]
