# Generated by Django 3.2.5 on 2022-05-11 07:07

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0013_alter_profilecategory_type'),
        ('user_settings', '0012_auto_20220228_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingmeta',
            name='default',
            field=jsonfield.fields.JSONField(default=None, verbose_name='默认值'),
        ),
        migrations.AlterField(
            model_name='settingmeta',
            name='namespace',
            field=models.CharField(choices=[('general', '通用'), ('password', '密码'), ('connection', '连接'), ('fields', '字段')], db_index=True, default='general', max_length=32, verbose_name='命名空间'),
        ),
        migrations.AlterUniqueTogether(
            name='setting',
            unique_together={('category', 'meta')},
        ),
    ]
