# Generated by Django 3.2.5 on 2022-05-20 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_settings', '0014_alter_local_password_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingmeta',
            name='namespace',
            field=models.CharField(choices=[('general', '通用'), ('password', '密码'), ('connection', '连接'), ('fields', '字段'), ('account', '账号')], db_index=True, default='general', max_length=32, verbose_name='命名空间'),
        ),
    ]
