swagger: '2.0'
basePath: /
info:
  version: '2.0'
  title: API Gateway Resources
  description: ''
schemes:
  - http
paths:
  /api/v3/open/tenants/:
    get:
      operationId: list_tenant
      description: 查询租户列表
      tags: [ ]
      responses:
        default:
          description: ''
      x-bk-apigateway-resource:
        isPublic: true
        allowApplyPermission: false
        matchSubpath: false
        backend:
          name: default
          method: get
          path: /api/v3/open/tenants/
          matchSubpath: false
          timeout: 0
        pluginConfigs: []
        authConfig:
          userVerifiedRequired: false
          appVerifiedRequired: true
          resourcePermissionRequired: false
        descriptionEn: Query the list of tenants

  /api/v3/open/tenants/users/display_name/:
    get:
      operationId: list_display_name
      description: 批量查询租户用户展示名
      tags: [ ]
      responses:
        default:
          description: ''
      x-bk-apigateway-resource:
        isPublic: true
        allowApplyPermission: false
        matchSubpath: false
        backend:
          name: default
          method: get
          path: /api/v3/open/tenants/users/display_name/
          matchSubpath: false
          timeout: 0
        pluginConfigs: [ ]
        authConfig:
          userVerifiedRequired: false
          appVerifiedRequired: true
          resourcePermissionRequired: false
        descriptionEn: Batch query tenant user's display_name
