swagger: '2.0'
basePath: /
info:
  version: '2.0'
  title: API Gateway Resources
  description: ''
schemes:
- http
paths:
  /api/v3/open/tenants/:
    get:
      operationId: list_tenant
      description: 查询租户列表
      tags: []
      responses:
        default:
          description: ''
      x-bk-apigateway-resource:
        isPublic: true
        allowApplyPermission: false
        matchSubpath: false
        backend:
          name: default
          method: get
          path: /api/v3/open/tenants/
          matchSubpath: false
          timeout: 0
        pluginConfigs: []
        authConfig:
          userVerifiedRequired: false
          appVerifiedRequired: true
          resourcePermissionRequired: false
        descriptionEn: Query the list of tenants

  /api/v3/open/tenant/users/-/display_name/:
    get:
      operationId: batch_query_user_display_name
      description: 批量查询用户展示名
      tags: []
      responses:
        default:
          description: ''
      x-bk-apigateway-resource:
        isPublic: true
        allowApplyPermission: false
        matchSubpath: false
        backend:
          name: default
          method: get
          path: /api/v3/open/tenant/users/-/display_name/
          matchSubpath: false
          timeout: 0
        pluginConfigs: []
        authConfig:
          userVerifiedRequired: false
          appVerifiedRequired: true
          resourcePermissionRequired: false
        descriptionEn: Batch query user's display_name

  /api/v3/open/tenant/users/{bk_username}/:
    get:
      operationId: retrieve_user
      description: 查询用户信息
      tags: []
      responses:
        default:
          description: ''
      x-bk-apigateway-resource:
        isPublic: true
        allowApplyPermission: false
        matchSubpath: false
        backend:
          name: default
          method: get
          path: /api/v3/open/tenant/users/{bk_username}/
          matchSubpath: false
          timeout: 0
        pluginConfigs: []
        authConfig:
          userVerifiedRequired: false
          appVerifiedRequired: true
          resourcePermissionRequired: true
        descriptionEn: Query user's information

  /api/v3/open/tenant/users/{bk_username}/departments/:
    get:
      operationId: list_user_department
      description: 查询用户所在部门列表
      tags: []
      responses:
        default:
          description: ''
      x-bk-apigateway-resource:
        isPublic: true
        allowApplyPermission: false
        matchSubpath: false
        backend:
          name: default
          method: get
          path: /api/v3/open/tenant/users/{bk_username}/departments/
          matchSubpath: false
          timeout: 0
        pluginConfigs: []
        authConfig:
          userVerifiedRequired: false
          appVerifiedRequired: true
          resourcePermissionRequired: true
        descriptionEn: query user's list of departments

  /api/v3/open/tenant/users/{bk_username}/leaders/:
    get:
      operationId: list_user_leader
      description: 查询用户 Leader 列表
      tags: []
      responses:
        default:
          description: ''
      x-bk-apigateway-resource:
        isPublic: true
        allowApplyPermission: false
        matchSubpath: false
        backend:
          name: default
          method: get
          path: /api/v3/open/tenant/users/{bk_username}/leaders/
          matchSubpath: false
          timeout: 0
        pluginConfigs: []
        authConfig:
          userVerifiedRequired: false
          appVerifiedRequired: true
          resourcePermissionRequired: true
        descriptionEn: Query user's list of leaders

  /api/v3/open/tenant/departments/{department_id}/:
    get:
      operationId: retrieve_department
      description: 查询部门信息
      tags: []
      responses:
        default:
          description: ''
      x-bk-apigateway-resource:
        isPublic: true
        allowApplyPermission: false
        matchSubpath: false
        backend:
          name: default
          method: get
          path: /api/v3/open/tenant/departments/{department_id}/
          matchSubpath: false
          timeout: 0
        pluginConfigs: []
        authConfig:
          userVerifiedRequired: false
          appVerifiedRequired: true
          resourcePermissionRequired: true
        descriptionEn: Query information of the department

  /api/v3/open/tenant/users/:
    get:
      operationId: list_user
      description: （分页）查询用户列表
      tags: []
      responses:
        default:
          description: ''
      x-bk-apigateway-resource:
        isPublic: true
        allowApplyPermission: false
        matchSubpath: false
        backend:
          name: default
          method: get
          path: /api/v3/open/tenant/users/
          matchSubpath: false
          timeout: 0
        pluginConfigs: []
        authConfig:
          userVerifiedRequired: false
          appVerifiedRequired: true
          resourcePermissionRequired: true
        descriptionEn: (Pagination) Query user's list
