# Generated by Django 3.2.13 on 2022-05-22 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0004_auto_20211021_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generallog',
            name='status',
            field=models.CharField(choices=[('succeed', '成功'), ('failed', '失败')], max_length=16, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='login',
            name='reason',
            field=models.CharField(blank=True, choices=[('bad_password', '密码错误'), ('expired_password', '密码过期'), ('too_many_failure', '密码错误次数过多'), ('locked_user', '用户已锁定'), ('disabled_user', '用户已删除'), ('should_change_initial_password', '需要修改初始密码'), ('admincontactrequired', '需要联系管理员续期')], max_length=32, null=True, verbose_name='登陆失败原因'),
        ),
    ]
