# Generated by Django 3.2.15 on 2022-09-20 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        # BUG: if uncomment this line, all migration will fail
        # while all migrations of the audit will not be migrated => all failed
        # ("profiles", "0026_auto_20220920_2251"),
        ("audit", "0005_auto_20220526_1048"),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name="login",
            index_together={("profile", "create_time")},
        ),
    ]
