# Generated by Django 3.2.13 on 2022-12-12 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0006_alter_login_index_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resetpassword',
            options={'get_latest_by': 'create_time', 'ordering': ['-create_time']},
        ),
        migrations.AddField(
            model_name='resetpassword',
            name='reason',
            field=models.CharField(blank=True, choices=[('bad_old_password', '原密码校验错误')], max_length=32, null=True, verbose_name='重置密码失败原因'),
        ),
    ]
