# Generated by Django 4.2.17 on 2024-12-12 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0007_auto_20221212_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='reason',
            field=models.CharField(
                blank=True,
                choices=[
                    ('bad_password', '密码错误'),
                    ('expired_password', '密码过期'),
                    ('too_many_failure', '密码错误次数过多'),
                    ('locked_user', '用户已锁定'),
                    ('disabled_user', '用户已禁用'),
                    ('deleted_user', '用户已删除'),
                    ('expired_user', '用户账号已过期'),
                    ('resigned_user', '用户已离职'),
                    ('should_change_initial_password', '需要修改初始密码'),
                ],
                max_length=32,
                null=True,
                verbose_name='登陆失败原因',
            ),
        ),
    ]
