# Generated by Django 4.2.17 on 2025-04-27 10:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("departments", "0006_alter_department_index_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="department",
            name="code",
            field=models.CharField(
                blank=True, max_length=255, null=True, unique=True, verbose_name="组织标识"
            ),
        ),
    ]
