# Generated by Django 3.2.20 on 2023-07-18 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='数据源名称')),
                ('code', models.CharField(max_length=256)),
                ('status', models.CharField(max_length=256, verbose_name='数据源状态')),
                ('owner', models.CharField(max_length=256, verbose_name='归属租户')),
                ('plugin_id', models.IntegerField(verbose_name='数据源插件id')),
                ('plugin_config', models.JSONField(verbose_name='数据源配置')),
            ],
        ),
        migrations.CreateModel(
            name='DataSourcePlugin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=256, verbose_name='数据源插件类型')),
                ('name', models.CharField(max_length=256, verbose_name='数据源插件名称')),
                ('config_meta', models.JSONField(verbose_name='数据源插件源配置')),
            ],
        ),
        migrations.CreateModel(
            name='DataSourceUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_source_id', models.CharField(max_length=256, verbose_name='数据源ID')),
                ('username', models.CharField(max_length=255, verbose_name='用户名')),
                ('display_name', models.CharField(max_length=256, verbose_name='全名')),
                ('email', models.EmailField(blank=True, default='', max_length=255, null=True, verbose_name='邮箱')),
                ('telephone', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='手机号码')),
                ('logo', models.TextField(blank=True, default='', max_length=256, null=True)),
                ('staff_status', models.CharField(default='', max_length=256)),
                ('is_deleted', models.BooleanField(default=False)),
                ('password', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='用户密码')),
            ],
        ),
    ]
