# Generated by Django 3.2.20 on 2023-08-11 07:10

from django.db import migrations


def forwards_func(apps, schema_editor):
    """
    初始化本地数据源插件
    """
    DataSourcePlugin = apps.get_model("data_source", "DataSourcePlugin")
    # FIXME: 待数据源插件确定后，重新初始化，国际化，这里暂时不使用枚举等
    if not DataSourcePlugin.objects.filter(id="local").exists():
        DataSourcePlugin.objects.create(
            id="local",
            name="本地数据源",
            description="支持用户和部门的增删改查，以及用户的登录认证",
        )


class Migration(migrations.Migration):

    dependencies = [
        ('data_source', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forwards_func)
    ]
