# Generated by Django 3.2.20 on 2023-08-11 07:10

from django.db import migrations

from bkuser.plugins.constants import DataSourcePluginEnum


def forwards_func(apps, schema_editor):
    """初始化本地数据源插件"""

    DataSourcePlugin = apps.get_model("data_source", "DataSourcePlugin")
    # FIXME: 待数据源插件确定后，重新初始化 & 国际化，且需要考虑存储 base64 编码的 logo
    if not DataSourcePlugin.objects.filter(id=DataSourcePluginEnum.LOCAL).exists():
        DataSourcePlugin.objects.create(
            id=DataSourcePluginEnum.LOCAL,
            name=DataSourcePluginEnum.get_choice_label(DataSourcePluginEnum.LOCAL),
            description="支持用户和部门的增删改查，以及用户的登录认证",
        )


class Migration(migrations.Migration):

    dependencies = [
        ('data_source', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forwards_func)
    ]
