# Generated by Django 3.2.25 on 2024-07-05 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_source', '0002_init_builtin_data_source_plugin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasource',
            name='domain',
        ),
        migrations.RemoveField(
            model_name='datasource',
            name='owner_tenant_user_id_rule',
        ),
    ]
