# Generated by Django 3.2.20 on 2023-11-21 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_source', '0002_init_builtin_data_source_plugin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='name',
            field=models.CharField(max_length=128, verbose_name='数据源名称'),
        ),
        migrations.AlterUniqueTogether(
            name='datasource',
            unique_together={('name', 'owner_tenant_id')},
        ),
    ]
