# Generated by Django 4.2.23 on 2026-01-30 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_source', '0002_init_builtin_data_source_plugin'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='datasource',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='datasource',
            name='username_suffix',
            field=models.CharField(default='', max_length=32, verbose_name='用户名后缀'),
        ),
    ]
