# Generated by Django 3.2.20 on 2023-08-25 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_source', '0002_inbuild_data_source_plugin'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasourceuser',
            name='code',
            field=models.CharField(default='', max_length=128, unique=True, verbose_name='用户标识'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='datasource',
            name='field_mapping',
            field=models.JSONField(default=list, verbose_name='用户字段映射'),
        ),
        migrations.AlterField(
            model_name='datasourceuser',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='手机号'),
        ),
        migrations.AlterUniqueTogether(
            name='datasourceuser',
            unique_together={('username', 'data_source'), ('code', 'data_source')},
        ),
    ]
