# Generated by Django 4.2.23 on 2025-08-26 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_source', '0002_init_builtin_data_source_plugin'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasourceuser',
            name='chinese_name_initial',
            field=models.CharField(blank=True, default='', max_length=16, null=True, verbose_name='中文名首字母缩写'),
        ),
    ]
