# Generated by Django 3.2.20 on 2023-12-01 03:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_source", "0003_auto_20231121_1201"),
    ]

    operations = [
        migrations.AddField(
            model_name="datasource",
            name="domain",
            field=models.CharField(default="", max_length=128, verbose_name="所属租户域名"),
        ),
        migrations.AddField(
            model_name="datasource",
            name="owner_tenant_user_id_rule",
            field=models.CharField(
                choices=[("uuid_hex", "uuid4 hex"), ("username", "用户名"), ("username@domain", "用户名@域名")],
                default="uuid4_hex",
                max_length=64,
                verbose_name="归属租户用户 ID 生成规则",
            ),
        ),
    ]
