# Generated by Django 3.2.20 on 2023-09-19 09:45

import blue_krill.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_source', '0003_auto_20230831_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localdatasourceidentityinfo',
            name='password',
            field=blue_krill.models.fields.EncryptField(blank=True, default='', max_length=255, null=True, verbose_name='用户密码'),
        ),
    ]
