# Generated by Django 3.2.25 on 2024-07-31 07:50

from django.db import migrations

from bkuser.plugins.constants import DataSourcePluginEnum


def forwards_func(apps, schema_editor):
    """添加本地数据源插件翻译"""

    DataSourcePlugin = apps.get_model("data_source", "DataSourcePlugin")

    # 本地数据源插件
    DataSourcePlugin.objects.filter(id=DataSourcePluginEnum.LOCAL).update(
        name_zh_cn=DataSourcePluginEnum.get_choice_label(DataSourcePluginEnum.LOCAL),
        description_zh_cn="支持用户和部门的增删改查，以及用户的登录认证",
        name_en_us="Local Data Source",
        description_en_us="Supports CRUD operations for users and departments, as well as user authentication.",
    )

    # Http数据源插件
    DataSourcePlugin.objects.filter(id=DataSourcePluginEnum.GENERAL).update(
        name_zh_cn=DataSourcePluginEnum.get_choice_label(DataSourcePluginEnum.GENERAL),
        description_zh_cn="支持对接通用 HTTP 数据源的插件，用户需要在服务方提供 `用户数据` 及 `部门数据` API",
        name_en_us="HTTP Data Source",
        description_en_us="Supports integration with general HTTP data sources. Users need to provide `User Data` and `Department Data` APIs at the service provider.",
    )


class Migration(migrations.Migration):

    dependencies = [
        ('data_source', '0004_add_translation_fields'),
    ]

    operations = [migrations.RunPython(forwards_func)]
