# Generated by Django 3.2.20 on 2023-09-26 03:08

import bkuser.utils.uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_source', '0004_alter_localdatasourceidentityinfo_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasourcedepartment',
            name='code',
            field=models.CharField(default=bkuser.utils.uuid.generate_uuid, max_length=128, verbose_name='部门标识'),
        ),
        migrations.AlterField(
            model_name='datasourceuser',
            name='code',
            field=models.CharField(default=bkuser.utils.uuid.generate_uuid, max_length=128, verbose_name='用户标识'),
        ),
        migrations.AlterUniqueTogether(
            name='datasourcedepartment',
            unique_together={('code', 'data_source')},
        ),
    ]
