# Generated by Django 3.2.20 on 2023-12-20 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_source', '0004_auto_20231201_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSourceUserDeprecatedPasswordRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('password', models.CharField(max_length=128, verbose_name='用户曾用密码')),
                ('operator', models.CharField(max_length=128, verbose_name='操作人')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_source.datasourceuser')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
