# Generated by Django 3.2.20 on 2023-09-27 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_source', '0005_auto_20230926_1108'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentRelationMPTTTree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_source', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.PROTECT, to='data_source.datasource')),
            ],
        ),
    ]
