# Generated by Django 3.2.20 on 2024-01-11 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_source', '0005_datasourceuserdeprecatedpasswordrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasourcedepartmentrelation',
            name='department',
            field=models.OneToOneField(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='department_relation', serialize=False, to='data_source.datasourcedepartment'),
        ),
    ]
