# Generated by Django 3.2.20 on 2024-01-24 02:15

import bkuser.apps.data_source.constants
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_source", "0006_alter_datasourcedepartmentrelation_department"),
    ]

    operations = [
        migrations.AddField(
            model_name="datasourceuser",
            name="status",
            field=models.CharField(
                choices=[("enabled", "启用"), ("disabled", "禁用")],
                default=bkuser.apps.data_source.constants.DataSourceUserStatus["ENABLED"],
                max_length=32,
                verbose_name="用户状态",
            ),
        ),
        migrations.AlterField(
            model_name="datasource",
            name="status",
            field=models.CharField(
                choices=[("enabled", "启用"), ("disabled", "未启用")],
                default="enabled",
                max_length=32,
                verbose_name="数据源状态",
            ),
        ),
    ]
