# Generated by Django 3.2.20 on 2024-03-13 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_source', '0007_auto_20240124_1015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasource',
            name='status',
        ),
    ]
