# Generated by Django 3.2.20 on 2024-03-26 11:16

import bkuser.apps.data_source.constants
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_source', '0007_auto_20240313_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='type',
            field=models.CharField(choices=[('real', '实体'), ('virtual', '虚拟'), ('builtin_management', '内置管理')], default=bkuser.apps.data_source.constants.DataSourceTypeEnum['REAL'], max_length=32, verbose_name='数据源类型'),
        ),
        migrations.AlterUniqueTogether(
            name='datasource',
            unique_together={('name', 'owner_tenant_id'), ('owner_tenant_id', 'type')},
        ),
    ]
