# Generated by Django 3.2.20 on 2023-10-24 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_source', '0007_inbuild_data_source_plugin'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasourcedepartmentuserrelation',
            name='data_source',
            field=models.ForeignKey(db_constraint=False, default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='data_source.datasource'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datasourceuserleaderrelation',
            name='data_source',
            field=models.ForeignKey(db_constraint=False, default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='data_source.datasource'),
            preserve_default=False,
        ),
    ]
