# Generated by Django 3.2.20 on 2024-03-27 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_source', '0008_auto_20240326_1916'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='datasource',
            unique_together={('owner_tenant_id', 'type')},
        ),
        migrations.RemoveField(
            model_name='datasource',
            name='name',
        ),
    ]
