# Generated by Django 3.2.20 on 2023-11-01 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_source', '0008_auto_20231024_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localdatasourceidentityinfo',
            name='password',
            field=models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='用户密码'),
        ),
    ]
