# Generated by Django 3.2.20 on 2023-09-20 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenant', '0003_auto_20230914_1013'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBuiltinField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='字段名称')),
                ('display_name', models.CharField(max_length=128, unique=True, verbose_name='展示用名称')),
                ('data_type', models.CharField(choices=[('string', '字符串'), ('number', '数字'), ('enum', '枚举'), ('multi_enum', '多选枚举')], max_length=32, verbose_name='数据类型')),
                ('required', models.BooleanField(verbose_name='是否必填')),
                ('unique', models.BooleanField(verbose_name='是否唯一')),
                ('default', models.JSONField(default='', verbose_name='默认值')),
                ('options', models.JSONField(default={}, verbose_name='配置项')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserCustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128, verbose_name='字段名称')),
                ('display_name', models.CharField(max_length=128, verbose_name='展示用名称')),
                ('data_type', models.CharField(choices=[('string', '字符串'), ('number', '数字'), ('enum', '枚举'), ('multi_enum', '多选枚举')], max_length=32, verbose_name='数据类型')),
                ('required', models.BooleanField(verbose_name='是否必填')),
                ('default', models.JSONField(default='', verbose_name='默认值')),
                ('options', models.JSONField(default={}, verbose_name='配置项')),
                ('tenant', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='tenant.tenant')),
            ],
            options={
                'unique_together': {('display_name', 'tenant'), ('name', 'tenant')},
            },
        ),
    ]
