name: bklogin_ci_check
on:
  push:
    branches: [ main, pre_*, ft_*, release/* ]
    paths:
      - "src/bk-login/**"
      - "src/idp-plugins/**"
  pull_request:
    branches: [ main, pre_*, ft_*, release/* ]
    paths:
      - "src/bk-login/**"
      - "src/idp-plugins/**"
jobs:
  check:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
          cache: 'pip'
          cache-dependency-path: 'src/bk-login/requirements_dev.txt'
      - name: create idp plugin symbolic link
        run: |
          ln -s $(pwd)/src/idp-plugins/idp_plugins $(pwd)/src/bk-login/bklogin
      - name: Install dependencies
        run: pip install -r src/bk-login/requirements_dev.txt
      - name: Format & Lint with ruff
        run: |
          ruff format src/bk-login --config=src/bk-login/pyproject.toml --no-cache
          ruff check src/bk-login --config=src/bk-login/pyproject.toml --no-cache
      - name: Lint with mypy
        run: |
          mypy src/bk-login --config-file=src/bk-login/pyproject.toml
  test:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Start MySQL Container
        uses: samin/mysql-action@v1.3
        with:
          mysql version: "8.0"
          mysql database: bk-login
          mysql user: root
          mysql password: root_pwd
          mysql root password: root_pwd
      - name: Start Redis Container
        uses: supercharge/redis-github-action@1.4.0
        with:
          redis-version: "3.2.0"
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: 'pip'
          cache-dependency-path: 'src/bk-login/requirements_dev.txt'
      - name: create idp plugin symbolic link
        run: |
          ln -s $(pwd)/src/idp-plugins/idp_plugins $(pwd)/src/bk-login/bklogin
      - name: Install dependencies
        run: pip install -r src/bk-login/requirements_dev.txt
      - name: Run unittest
        working-directory: src/bk-login
        run: |
          # random secret
          export BK_APP_SECRET="fod6MKVTVi_3M5HgGoj-qI7b3l0dgCzTBwGypnDz4vg="
          export BK_USER_APP_SECRET="Vi_3M5HgGogCzTBwGypnDz4vgfod6MKVTj-qI7b3l0d="
          # random secret key
          export BKKRILL_ENCRYPT_SECRET_KEY="tttHSBLiVdQPItrfy7n9dV7AxAUMZpYVkD6IHMbL0VE="
          export BK_DOMAIN="example.com"
          export BK_COMPONENT_API_URL=""
          export MYSQL_PASSWORD=root_pwd
          export MYSQL_HOST="127.0.0.1"
          export DJANGO_SETTINGS_MODULE=bklogin.settings
          pytest ./tests
